### ISSUE TITLE
What to do on `slog_extra::Async` channel overflowing.

### ISSUE THREAD

**Issue by dpc** [slog-rs/slog#101]
Could be controlled by a builder pattern giving options:

* block sender
* drop logging records (and log one message about the overflow?)
* keep overflowing
* + number of entries that are considered an overflow

**Comment by przygienda** [comment]
From large systems: start dropping, @ end of dropping generate an error with "X messages dropped due to overload" ...

**Comment by dpc** [comment]
Thanks. That seems most reasonable ATM, yes.

I think it can be done with a builder pattern to configure it, and make what you described a default.

**Comment by dpc** [comment]
@przygienda I guess some form of histereza is neccessary too. Eg. wait for the whole buffer to get drained before start logging again. Makes sense?

**Comment by dpc** [comment]
This is fixed in `slog-async v0.2.0-alpha2`
