### ISSUE TITLE
`slog-term`: Bright vs Dim ANSI color codes 

### ISSUE THREAD

**Issue by dpc** [slog-rs/slog#102]
Migrated from https://github.com/slog-rs/term/issues/2

`slog-term` uses ANSI codes which might be handled differently on Windows. Using `term` package instead would be better.

**Comment by dpc** [comment]
WIP: https://github.com/slog-rs/term/commit/dc3d8d5417df24cc76282d6dbbb4903271d7fcd1

**Comment by dpc** [comment]
This shall be fixed by v2 release.

**Comment by NCommander** [comment]
I wanted to note that this is actually a problem with slog and referencing the original bug as I just recently brought a rust project from Linux to Windows.

When I run the app in MinTTY or another cmd.exe replacement, I get the expected color output. If you've got a test version of slog-term, I'll be happy to test it.:

Here's the exact output I get on Windows cmd.exe in black and white:
Feb 21 00:43:15.453←[32m INFO ←[39m←[1mHammer v0.1.0 started←[0m
←[1mmodule←[0m: HammerConfiguration

**Comment by dpc** [comment]
`slog`, `slog-json` `slog-async` already have `slog 2.0.0-alpha1` port. `slog-term` is in the workings. Shouldn't take too long.

**Comment by dpc** [comment]
slog-term v2.0.0-alpha1 have been published and this should be fixed there.

`slog-term` now uses `term` crate by default. Would be awesome if someone could check Windows.

**Comment by NCommander** [comment]
I'll check either later today or tomorrow. My Windows system is currently
down at the moment as I'm upgrading it's VM. Watch this space :)

**Comment by dpc** [comment]
@NCommander ping. I have some users sending PRs so I believe it's working.

**Comment by dpc** [comment]
Closing as fixed just to tidy up the list. Always feel free to reopen in case of need. :)
