### ISSUE TITLE
nightly breaking slog-1.4 

### ISSUE THREAD

**Issue by przygienda** [slog-rs/slog#103]
error[E0178]: expected a path on the left-hand side of `+`, not `(Fn(D::Error) -> E)`
   --> /Users/prz/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-1.4.0/src/_drain.rs:119:17
    |
119 |     map_fn: Box<(Fn(D::Error) -> E) + 'static+ Send+Sync>,
    |                 ^^^^^^^^^^^^^^^^^^^ expected a path
    |
    = help: perhaps you forgot parentheses? (per RFC 438)

looks to me like compiler bug though ...

**Comment by dimfeld** [comment]
I'm seeing this too with the nightly build from 2017-01-17 (x86_64-apple-darwin). It works fine with 2017-01-12. I haven't tried any builds in between.

**Comment by dpc** [comment]
Thanks for reporting it. I reported to rust: https://github.com/rust-lang/rust/issues/39169

Workaround would be to pin the nighty version to yesterday one with `rustup`.

**Comment by dpc** [comment]
1.4.1 released
