### ISSUE TITLE
Use `termion` in `slog-term`.

### ISSUE THREAD

**Issue by ticki** [slog-rs/slog#105]
So I'm interested in using Slog for TFS, the file system for Redox, but slog-term doesn't support Redox right now, and replacing the backend with [Termion](https://github.com/ticki/termion) would do the job. It should be a relatively limited amount of changes to.

I'm not familiar with the codebase right now, but I'll try to replace it when I get time, either tomorrow or the day after.

**Comment by dpc** [comment]
Have you seen #102  ?

**Comment by dpc** [comment]
Anyone that can write a PR that works on Linux (VT100), Windows (cmd.exe), Mac and Redox will get a cookie!

**Comment by dpc** [comment]
Good news. This is going to get fixed in `slog v2`. I have gave it some thought and it will be totally possible to implement `termion` coloring in `slog-term` for `slog v2`. Stay tuned.

**Comment by ticki** [comment]
very nice!

**Comment by dpc** [comment]
slog-term v2.0.0-alpha1 have been published. It should be now fairly easily to add `TermionDecorator` (just copy `TermDecorator` and modify couple of bits).

I'm short on time so I don't plan to do it myself, but I'd be happy to accept a PR. It should be also possible to put it in separate crate too: eg `slog-termion` if someone finds it preferable. Generally, it should be now possible to port this stuff to any IO backend.

**Comment by ticki** [comment]
Will look into it.

**Comment by dpc** [comment]
@ticki Any luck? (No pressure, just checking :) )
