### ISSUE TITLE
async logging

### ISSUE THREAD

**Issue by ticki** [slog-rs/slog#116]
Since writing logs is potentially pretty expensive, having ability to do asyncronous logging would be nice.

In particular, I'm thinking of `futures` integration, which provides a pretty nice boilplate for this kind of stuff.

**Comment by dpc** [comment]
https://docs.rs/slog-async/ (slog v2) , https://docs.rs/slog-extra (slog v1). Feedback, even negative is very welcome, especially about v2.

I don't really see how `futures` would be useful here. You would get a `Future` of your `info!(...)` being eventually written or something? If there is something that I'm missing I'd be happy to know!

Closing for now. Feel free to keep commenting or reopen if there's anything to be done.

**Comment by ticki** [comment]
> You would get a Future of your info!(...) being eventually written or something?

Yeah. That way I can chain and say "first do this operation after logging" etc.

**Comment by ticki** [comment]
> Async will send all the logging records to a wrapped drain running in another thread.

That sounds like a hack to be honest.

With futures, one can store it in their own thread pool.

**Comment by dpc** [comment]
> >  Async will send all the logging records to a wrapped drain running in another thread.
> 
> That sounds like a hack to be honest.

Why is that? `Drain`s are composable so wrapping one drain with another is the standard way to do things. `Async` just let drains cross the boundary of a thread, and offloading actual work to another thread.

From the logging user perspective logging statements like `info!(....)` must just execute quickly, and I don't anyone will want to play with state machine for every logging statements. As long as this is not what you want to achieve, then you should be implement whatever else you think about just by adding new `Drain` implementation(s). I'd be happy to answer any questions you might have.

Right now `Async` `Drain` will send logging `Record` to a worker thread through `sync::mpsc::SyncChannel`, and worker thread will just keep processing them as they arrive. That makes it possible to replace any heavy part of logging with ~100ns channel send.

What is your plan?

**Comment by tmccombs** [comment]
> With futures, one can store it in their own thread pool.

Why would you ever want multiple threads doing the actual logging at the same time? You would need to synchronize the threads anyway when actually writing the logs.
