### ISSUE TITLE
`Logger::to_erased()` should not consume `self`

### ISSUE THREAD

**Issue by lo48576** [slog-rs/slog#119]
[`Logger::to_erased()` consumes `self`](https://github.com/slog-rs/slog/blob/7d17a2ad03aaa3680f5dbcc8ca5276acc3a2fedd/src/lib.rs#L875), but this function clones `self` and doesn't require consuming `self`.
Therefore, this should be `pub fn to_erased(&self)`.

**Comment by dpc** [comment]
You're right. Thanks!
