### ISSUE TITLE
The syslog logger panics if no syslog is available

### ISSUE THREAD

**Issue by vorner** [slog-rs/slog#121]
My development computer doesn't have a syslog installed. Therefore connecting to it fails. However, it was the first time I saw a program to crash because of that. The usual behaviour is to simply not log to syslog when it is not available.

I think the library should either ignore such error or return `Result`, but panicking is a bit too harsh.

The relevant line is this (the `unwrap`): https://github.com/slog-rs/syslog/blob/master/lib.rs#L155

**Comment by dpc** [comment]
Right. Thanks for reporting it.

**Comment by dpc** [comment]
Fixed in `slog-syslog 0.10.0`

**Comment by vorner** [comment]
Thanks, I can confirm it works for me. But there seems to be some confusion around versions (docs.rs thinks the `0.10.0` isn't the newest).

**Comment by dpc** [comment]
Yeah... I yanked 1.0.0-* versions at some point, as I decided this crate is not ready yet for 1.0.0. crates.io recently fixed handling such cases, but docs.rs does not understand yanked crates. It's unfortunate.
