### ISSUE TITLE
slog-syslog doesn't handle a stream socket

### ISSUE THREAD

**Issue by vorner** [slog-rs/slog#122]
I have a device that uses `SOCK_STREAM` socket on `/dev/log`. The syslog-ng config is snippet is:

```
source src {
	internal();
	unix-stream("/dev/log");
};
```

If I try to use `slog-syslog` on that system, initialization fails with „Protocol wrong type for socket“. The classic C `syslog` function on that system works well.

**Comment by dpc** [comment]
I'd be happy to have this fixed, however might take me a while to get into it. If you want I encourage you to investigate `slog-syslog` source code and try coming up with a PR. Look for help on gitter channel.

**Comment by vorner** [comment]
I've sent a [PR](https://github.com/Geal/rust-syslog/pull/22) to the syslog dependency, that should fix it I think. However, the author is a bit silent there :-(.

**Comment by dpc** [comment]
Oh. It is vacation season. Geal is an author of `nom` and many other popular crates, so I'm sure he's swamped with github notifications all the time. Politely reminding ourselves from time to time, should do. Hi @Geal!

**Comment by Geal** [comment]
ohai. Taking a look today :)

**Comment by Geal** [comment]
ok, so there's a version 3.3.0 of syslog including that feature
