### ISSUE TITLE
Adding new key-value pairs in an allocation-free way

### ISSUE THREAD

**Issue by tbu-** [slog-rs/slog#124]
It seems to me that `Logger::new` allocates in the default case because it has to clone an `Arc`.

I want to add some information to my logger using `Logger::new` (or some other appropriate method), but incurring an allocation would be too much of a performance hit.

Just from thinking about it, it doesn't sound impossible: `Logger` could keep a linked list of (groups of) new key-value pairs, and when you add your own key-value pairs, it just prepends them.

Is something like that possible?

**Comment by dpc** [comment]
> Just from thinking about it, it doesn't sound impossible: Logger could keep a linked list of (groups of) new key-value pairs, and when you add your own key-value pairs, it just prepends them.

That's how it works right now. The thing is - if you want to prepends it, you need it in `Arc` already. Please see the source code and investigate, I'd be happy if there's something that could be improved.

If you can't tolerate allocation, I'd advice using `slog v2` and create key-value object using `kv!` and just pass it every `info!(...)` and friends like described: https://docs.rs/slog/2.0.0-3.1/slog/macro.log.html#own-implementations-of-kv-and-value

**Comment by dpc** [comment]
Also check https://github.com/slog-rs/slog/blob/master/examples/struct-log-self.rs . It's kind of related. Basically what I'm saying is: anything that goes into `Logger` directly has to be `Arc`ed since it has to be chainable by children loggers. But `slog` in `slogv2` got the `KV` concept much more flexible and it's easy to operate on `struct`s that implement `KV` and use them directly in `info!(...)` and others.

**Comment by tbu-** [comment]
It seems that things passed to `new` and things passed to the `info!(...)`-like macros is treated differently – one is passed to the `Drain` via the passed `&OwnedKVList`, the other via the `BorrowedKV` obtained through the passed `&Record`.

Why is one of them passed as `&OwnedKVList`? Is it important that it's owned?

One of my use case looks like this: I have a server application, and it should log. Each time I receive a message from one of the clients, I want to add the client's IP address or client ID to the logging context. Since this happens really often, and log messages aren't that frequent, it would be useful if this step "adding client information to the logging context" was really low-cost, i.e. definitely not involving an allocation.

I thought about wrapping the logger in my own custom struct also implementing logger, however, I'd need to construct a owned key-value store in order to pass it to the underlying logger when a message comes in, which sounds like it does an allocation.

**Comment by dpc** [comment]
Yes. Owned and borrowed are different: one is taking `&KV`, the other is taking a `KV` and making it `Arc<KV>` so it can be chained. They just use different tradeoffs - one is supposed to be more permanent, the other ephemeral.

b!: https://github.com/slog-rs/slog/blob/feeaf708231913adfb6f34b4ea9a279492b11c89/src/lib.rs#L209
o!: https://github.com/slog-rs/slog/blob/feeaf708231913adfb6f34b4ea9a279492b11c89/src/lib.rs#L187
kv!: https://github.com/slog-rs/slog/blob/feeaf708231913adfb6f34b4ea9a279492b11c89/src/lib.rs#L228

What I am saying: you can construct your own type implementing `KV`, and pass it like that:

https://github.com/slog-rs/slog/blob/feeaf708231913adfb6f34b4ea9a279492b11c89/src/tests.rs#L164

```
info!(log, "message"; "foo" => "bar", &x, &x, "aaa" => "bbb");
```

You will have to pass it every time, but you don't need to specify the key so it's quite short.

**Comment by dpc** [comment]
I'm actually quite interested in helping make stuff like that more ergonomic.

Eg. note that you should be able to create something like:


```
impl MyServer {
    fn info(&self, msg : &'static str) {
      self.logger.log(&record!(slog::Info, "", &format_args!("{}",msg), b!(self.client))
    }

    fn handle_msg() {
       self.info("message received");
    }

}
```

or similar, to bring the noise to the minimum.

**Comment by dpc** [comment]
How did it go? Since there is nothing actionable here, I'm closing, but feel free to continue the discussion, reopen, discuss on gitter channel.
