### ISSUE TITLE
Question:  Performance of slog

### ISSUE THREAD

**Issue by rohitjoshi** [slog-rs/slog#126]
Thanks for creating an incredible logging framework. 

Have you done any performance analysis/comparison?  I came across [mini-async-log C++](https://github.com/RafaGago/mini-async-log) which seem to be pretty fast and here is [comparison](https://github.com/RafaGago/mini-async-log#threads-8-msgs-1m) against other C++ logging libraries.

**Comment by dpc** [comment]
I have seen  `mini-async-log` on r/cpp and it's not obvious how to compare with it. The thing is: slog is an ecosystem, other libraries are just libraries. Slog doesn't force you to use one disk writer, or asynchronous implementation. It does provide you with reasonable ones, but you're free to come up with (or reuse existing) ones more tailored to your need. Conceptually there's nothing preventing you from reimplementing  `mini-async-log C++ as a `Drain` for `slog`

Benchmarking in `mini-async-log` is doing is a very synthetic case. Many threads pumping log records at the full speed. Unless that is really what the app you're working on is doing, it's quite irrelevant. For typical app, what matter is how quickly any logging statement executes on the thread it is on. I keep the record of such numbers here: https://github.com/slog-rs/slog/wiki/Bench-log

Now for synthetic case, `slog-async` uses standard library `std::sync::mpsc::sync_channel`, so throughput and multiple thread handling will be mostly benchmarking Rust standard library vs custom channel implementation by `mini-async-log`. I am sure standard library will perform reasonably well.
