### ISSUE TITLE
Create multiple drain, and channel support

### ISSUE THREAD

**Issue by sbant** [slog-rs/slog#127]
1.  For example, I need one console drain, and multiple file drains at the same time.
Currently, we can use slog::Duplicate to combine two drains, but when need many drains?

2.  I used to use Boost.Log in C++, it support channel, so can log the message to different sink(drain), some to a file, some to another file, etc.

I copy the description from Boost.Log help:
    Sometimes it is important to associate log records with some application component, such as the module or class name, the relation of the logged information to some specific domain of application functionality (e.g. network or file system related messages) or some arbitrary tag that can be used later to route these records to a specific sink.

Is there something equal in slog?

**Comment by dpc** [comment]
You can either have `Duplicate(one_thing, Duplicate(second_thing, third_thing))` or you can create your own `struct MyComplexDrain` and `impl Drain for MyComplexDrain` where you forward messages according to your requirements. Use `Duplicate` as a reference: https://github.com/slog-rs/slog/blob/0ffbd80fabf609f60410f2f725a35d7a2e70a6db/src/lib.rs#L1412 .

**Comment by dpc** [comment]
For complex logic, when implementing `Drain::log`: https://docs.rs/slog/2.0.2/slog/trait.Drain.html#tymethod.log you will have a `Record` argument which will give you things like `tag`, `file,`line` etc. https://docs.rs/slog/2.0.2/slog/struct.Record.html

**Comment by njam** [comment]
I also think it'd be nice to have a `Multiply` drain shipped with slog.
Something like
```rs
let multiply = MultiplyBuilder::new()
  .add(drain1).add(drain2).add(drain3)
  .build();
```

**Comment by dpc** [comment]
@njam You might be able to come up with an api like that, building a `Duplicate` (potentially nested).

Maybe:

```
trait DrainExt {
   fn chain<D: Drain>(self, d: D) -> Duplicate<Self, D> {
      Duplicate(self, d)
   }
}
```
