### ISSUE TITLE
Versioning of slog v2 crates unclear, can't edit Wiki

### ISSUE THREAD

**Issue by sanmai-NL** [slog-rs/slog#129]
I couldn't figure out quickly how to edit the Wiki on slog v2. If I have to clone the Wiki for that, maybe in-repo markup files are more practical than a Wiki?

I'm trying to since the list of current versions on the Wiki is outdated. What about just providing links to the crates on docs.rs or crates.io to look up the current versions?

I'm running into these issues while trying to depend on simply ‘the latest’ slog v2 crates in `Cargo.toml`.

**Comment by dpc** [comment]
https://crates.io/search?q=slog I think that's the best list. :)

Let me look into a wiki thing ...

**Comment by dpc** [comment]
Wiki should now be editable. Thanks for pointing it out!

**Comment by przygienda** [comment]
Besides, it looks like slog-atomic went from 0.* to 2.* directly and I'm being still on slog 1.5 cannot make it work now since it picks 2.0 and doesn't manage to compile ...

**Comment by dpc** [comment]
@przygienda  You should be able to pin it as `slog-atomic = "0.x"`, no?

**Comment by przygienda** [comment]
Our MailScanner believes that the attachment to this message sent to you

**Comment by sanmai-NL** [comment]
So the issue can be closed now?
