### ISSUE TITLE
Support for nested KV pairs

### ISSUE THREAD

**Issue by mthebridge** [slog-rs/slog#130]
It would be really nice to be able to nest `KV` pairs to allow logging custom structures without worrying about clashing keys.

For example,  I might have some custom identifier which consists of a string and a numeric ID.  It would be nice to be able to do this kind of thing and have `slog_json` write this as nested JSON:

```rust
struct ObjId { 
  name: String,
  id: u64,
}

let obj: ObjId = get_obj_id();
info!(logger, "Event happened for object", 
      "event_obj" => ("name" => obj.name, "id" => obj.id))
```

In this case I know I could use `obj_name` and `obj_id` as keys, but in more complicated cases I'll be adding objects in this way into loggers that can be inherited by child loggers, and this would make it easy to avoid clashes between keys.

**Comment by dpc** [comment]
Keys technically don't have to be unique.

There have been requests like that before: https://github.com/slog-rs/slog/issues/77 https://github.com/slog-rs/slog/issues/22 .

To do it right slog would have to basically support full-blown sequences, and include a serialization framework, or reuse existing one. Lots of complications. Maybe one day...

For now, you could fork `slog-json` and customize for you own needs. The order of keys is preserved, so you could eg. designate a prefix for keys that would be merged into one struct, and then output them in a right way in the drain.

**Comment by tmccombs** [comment]
Nested structures don't make sense for all types of structured logs. How would you send nested data to journald, or a terminal that prints pairs in the form <K=V>.

**Comment by mthebridge** [comment]
Thanks for the speedy replies, and the links to the other issues.  Full structure/serialization support would be awesome but I can see that's a lot of work - I was just checking I hadn't missed something. :)   I think adding prefixes to keys will be good enough for my use case.  Modifying the JSON drain to reconstruct the nested structure is a nice idea - I might look into that if I get time.

**Comment by dpc** [comment]
itshappening.gif

Check out `serde` branch, which might soon get merged into master.
