### ISSUE TITLE
Features should be documented elsewhere too

### ISSUE THREAD

**Issue by sanmai-NL** [slog-rs/slog#136]
`slog` has two types of impactful features (they may cause messages to not be displayed in released binary executables). These are only documented [for `slog_stdlog`](https://docs.rs/slog-stdlog/2.0.0/slog_stdlog/#compile-time-log-level-filtering). I propose to document them in the API docs for `slog` and to refer to this section from other crates.

**Comment by dpc** [comment]
https://docs.rs/slog/2.0.5/slog/#notable-details

**Comment by sanmai-NL** [comment]
Thanks! Two issues though made this harder to find though.

1. `release_max_level_warn` cannot be found using the search bar at the top of the docs.
2. The heading ‘Notable details’ is aspecific and abstract. A (bigger) heading ‘Features’ is a better choice IMO. The preceding heading about ‘features’ can be renamed ‘Functionality and related crates’ (and should perhaps not be in the API docs in its current shape, since it mixes promotion and description).

**Comment by dpc** [comment]
From my experience: not many people actually read documentation from end to end anyway. The whole thing is a gotcha, unfortunately, and I encourage users to ask questions on gitter channel. :)

Maybe when compiling with the defaults a warning/notice should be printed so users have to set their own compile time logging level if they want to avoid it... . But then they will mind additional work.

Anyway, I'm always for docs improvements, but it's always similar story: people have different needs, approaches, read different parts. I don't want to be moving things back and forth and generally would like everything to be on docs.rs ("advertisement", functionality, examples, whatever).

I am open to renaming sections / improving structure though. Feel free to submit a PR. :)
