### ISSUE TITLE
`slog_term::TermDecorator.stderr().try_build()` fails, API comes short

### ISSUE THREAD

**Issue by sanmai-NL** [slog-rs/slog#137]
`slog_term::TermDecorator::new().stderr().try_build()` returns an `Option` while it should return a `Result`, since it is fallible. The current API makes debugging failure impossible, and failure means logging is impossible, and without logging ... software isn't quite usable. 😁

Currently, it appears to be impossible to use `slog_term` from within an Alpine Linux 3.5 Docker container because it fails to open `stderr` as well as `stdout`. `eprintln!` and `println!` work fine, however. I have tried setting env var `TERM` to `xterm`, `xterm-256color` and `ansi`, but that does not prevent the issue.

See Stebalien/term#57 that seems to get at the underlying issue and contains a workaround.

**Comment by dpc** [comment]
Seems to me, other than API problem, it's `term` underlying issue.

I would be happy to merge a PR to address this in some satisfying way. Since we can't break API, a new, alternative to `try_build` could be introduced to return `Result` and `try_build` deprecated at some point.

**Comment by dpc** [comment]
Docker issues should be fixed in 2.3.0 now. Just use `build` and it will fall back to using `std::io::stderr/stdout`.
