### ISSUE TITLE
slog_bunyan outputs host instead of hostname

### ISSUE THREAD

**Issue by peletomi** [slog-rs/slog#138]
Bunyan outputs a field named hostname instead of host. [See doc](https://github.com/trentm/node-bunyan#introduction). Because of this bunyan cli does not format the output correctly.

**Comment by dpc** [comment]
https://github.com/slog-rs/bunyan/blob/master/lib.rs#L34

If you can provide a PR, that would be great. Otherwise, I'll get to it at some point.

**Comment by peletomi** [comment]
Created a PR: https://github.com/slog-rs/bunyan/pull/1
