### ISSUE TITLE
Example in documentation of `slog_stdlog::init()` wrong

### ISSUE THREAD

**Issue by robinst** [slog-rs/slog#140]
I'm pretty sure this example no longer works with slog 2: https://docs.rs/slog-stdlog/3.0.0/slog_stdlog/fn.init.html

It compiles, but it won't log anything because there's no global logger set via slog-scope. Not sure it even worked with slog 1.

**Comment by dpc** [comment]
Thanks for reporting it! Fixed.

**Comment by robinst** [comment]
I saw your commit: https://github.com/slog-rs/stdlog/commit/53950a9b4b76285031035e26b2c0fd4e3f7a8c60

But the example is still incomplete, because it doesn't set a logger via slog-scope. If someone tries that example and copy it into their project, they will be scratching their head as to why the `info!` does nothing. It would be nice to have a full example like here: https://github.com/slog-rs/misc/blob/master/examples/oldlogging.rs

**Comment by dpc** [comment]
How about now?

**Comment by robinst** [comment]
Looks like the following things are missing:

* `#[macro_use] extern crate slog;`
* `use slog::Drain;`
* Calling `.build()` on `slog_term::TermDecorator::new()`

But even then it doesn't compile because `TermDecorator` is not `Sync`..

**Comment by dpc** [comment]
Errr... :D

**Comment by dpc** [comment]
Argh. I had to do `make test`, not `make doc`... :D

**Comment by dpc** [comment]
Maybe now? :)

**Comment by robinst** [comment]
That's it 😄

**Comment by dpc** [comment]
Done. Thanks for help!
