### ISSUE TITLE
Logging to file with slog_scope::set_global_logger doesn't work well in multithreaded environment

### ISSUE THREAD

**Issue by mkpankov** [slog-rs/slog#144]
I set up global scoped logger to file in test function. Then I log there and check that logged message is present in file after log guard dies.

From time to time, different tests fail.

test.rs:

```rust
...
fn setup_logging(test_name: &str, log_name: &str) -> (slog::Logger, PathBuf) {
    DirBuilder::new()
        .recursive(true)
        .create(format!("tests/workspace/{}", test_name))
        .unwrap();
    let log_path = PathBuf::from(format!("tests/workspace/{}/{}", test_name, log_name));
    let file = File::create(&log_path).unwrap();

    let decorator = slog_term::PlainSyncDecorator::new(file);
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    (slog::Logger::root(drain, o!()), log_path)
}

fn search_for_string_in_file(mut file: File, needle: &str) -> bool {
    let mut contents = String::new();
    file.read_to_string(&mut contents).unwrap();
    contents.contains(needle)
}

fn perform_test(test_name: &str) {
    let (log_global, log_global_path) = setup_logging(test_name, "log_global_output");

    {
        let _log_guard = slog_scope::set_global_logger(log_global);

        slog_scope::scope(&slog_scope::logger().new(slog_o!("scope" => "1")), || {
            slog_test::perform_scenario();
        });
    }

    let log_file = File::open(log_global_path).unwrap();
    // This assert fails from time to time
    assert!(search_for_string_in_file(log_file, "Foo dropping!"));
}

#[test]
fn test_1() {
    let test_name = "test_1";
    perform_test(test_name);
}
...
```

lib.rs:

```rust
#[macro_use]
extern crate slog;
#[macro_use]
extern crate slog_scope;

struct Foo {}

impl Foo {
    fn new() -> Self {
        info!("Foo creating!");
        Self {}
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        info!("Foo dropping!")
    }
}

pub fn perform_scenario() {
    let s = Foo::new();
}
```

Complete test project is here: https://github.com/mkpankov/slog_test

Example failed run:

```
± % ➜  RUST_TEST_THREADS=5 cargo test                                                                                                                                                                        !10119
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/slog_test-429ead50722b04a9

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test-38bee35988c4d3e2

running 5 tests
test test_2 ... ok
test test_1 ... ok
test test_3 ... ok
test test_5 ... ok
test test_4 ... FAILED

failures:

---- test_4 stdout ----
	thread 'test_4' panicked at 'assertion failed: search_for_string_in_file(log_file, "Foo dropping!")', tests/test.rs:44
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_4

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test test'
± % ➜  cat tests/workspace/test_4/log_global_output

± % ➜  ls -l tests/workspace/test_4/log_global_output
-rw-rw-r-- 1 mkpankov mkpankov 0 авг.  10 17:27 tests/workspace/test_4/log_global_output

```

I understand you don't recommend using `slog_scope` in libraries, but in this case location of `slog_test::perform_scenario` is irrelevant. It's there to model my project that has this problem, and my project is a program. `lib.rs` is there only for decomposition and testing.

I understand slog's scoped global logger is thread-global (not process-global), is that correct?

As tests are run in multiple threads by default, I suspect there's some kind of race condition. Running tests as `RUST_TEST_THREADS=1 cargo test` fixes the problem.

**Comment by dpc** [comment]
`slog_scope::set_global_logger` is a global resource. In every test you're performing, you're replacing it, and clearing it altogether when the test ends. Since all tests are run concurrently, this gives unpredictable behavoir.

From what I can see, just rely on the enclosing scope entirely.  `slog_scope::scope` does not require you to reuse the existing scope logger.

So instead:

```
        slog_scope::scope(&slog_scope::logger().new(slog_o!("scope" => "1")), || {
(...)
```

you can do:

```
        slog_scope::scope(log_global, || {
(...)
```

and ommit the `let _log_guard = slog_scope::set_global_logger(log_global);` entirely.

If for any reason you do require global logger set, make it via some form of reference counting or https://doc.rust-lang.org/std/sync/struct.Once.html

**Comment by mkpankov** [comment]
@dpc Thank you for thorough answer!

Your suggestion works for me.

However, allowing `set_global_logger` w/o unsafe surprises me. To me this looks a lot like `static mut`, which can't be written w/o unsafe or mutexes.

What do you think of making `set_global_logger` `unsafe fn`?

**Comment by dpc** [comment]
I'm glad it helped.

`set_global_logger` is using `ArcCell` underneath: https://github.com/slog-rs/scope/blob/master/lib.rs#L106 , which allows atomic swapping. Which means, your program can't get corrupted or crash no matter how you abuse `set_global_logger`. It is however suspectible to functional race condition - where you get non-deterministic runtime behavior. Such behavior is however outside of the meaning of `unsafe`.
