### ISSUE TITLE
_Why_ is the term thingy printing to fd #1 and fd #2

### ISSUE THREAD

**Issue by przygienda** [slog-rs/slog#154]
Have a look @ 

<script src="https://gist.github.com/przygienda/bbce4cb5b7de647340d7086bf30786d3.js"></script>

I see this thing outputing 2! versions of the log, one to fd # 2, the other to fd # 1, like this 

```
prz-mbp:slog-sandbox prz$ ./target/debug/slog-sandbox >/dev/null
thread: 2
 Dec 07 20:29:42.134 WARN check me: 2
thread: 0
 Dec 07 20:29:42.136 WARN check me: 0
Dec 07 20:29:42.136 INFO spawned
thread: 1
 Dec 07 20:29:42.136 WARN check me: 1
thread: 4
 Dec 07 20:29:42.136 WARN check me: 4
thread: 3
 Dec 07 20:29:42.136 WARN check me: 3
prz-mbp:slog-sandbox prz$ ./target/debug/slog-sandbox 2>/dev/null
check me: 0
check me: 3
check me: 1
spawned
check me: 2
check me: 4
```

What gives? I have only a CompactFormat and TermDecorator drain which should really go to fd#0 ? (why #2?) and why two copies? That used to work before 2.* 

Help (I guess :-P )

**Comment by przygienda** [comment]
Worse, if preemption interleaves, the color marking falls apart and so on ...

**Comment by dpc** [comment]
```
[I] dpc@futex ~/t/foo (master)> cargo run 1>/dev/null
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/foo`
Dec 07 20:44:21.531 INFO spawned
thread: 1
 Dec 07 20:44:21.532 WARN check me: 1
thread: 0
 Dec 07 20:44:21.532 WARN check me: 0
thread: 3
 Dec 07 20:44:21.532 WARN check me: 3
thread: 2
 Dec 07 20:44:21.532 WARN check me: 2
thread: 4
 Dec 07 20:44:21.532 WARN check me: 4
[I] dpc@futex ~/t/foo (master)> cargo run 2>/dev/null
spawned
check me: 2
check me: 1
check me: 0
check me: 3
check me: 4
```

**Comment by dpc** [comment]
Interesting...

**Comment by dpc** [comment]
Ha! https://github.com/slog-rs/kvfilter/blob/0.4.0/src/lib.rs#L132

**Comment by przygienda** [comment]
cool, I looked in other modules ... Lemme pul dev into main and release new version then ...

**Comment by przygienda** [comment]
fixed

**Comment by Michael-F-Bryan** [comment]
I think I've encountered the same issue when running tests and using a filtered `slog_term::TestStdoutWriter`. 

All `TRCE` messages are being printed directly to stdout and being interleaved with the normal test runner's output. then when a test fails it'll print `INFO`, `DEBG`, `WARN`, and `ERROR` messages under the `--- my_test_name stdout ---` section (where normal `println!()` statements go). It appears that the drain is multiple file descriptors and the test runner only intercepts one set of output.

Versions Used:

```toml
slog = "2.1.1"
slog-term = "2.3.0"
```

**Comment by dpc** [comment]
@Michael-F-Bryan - The issue here was a leftover code in `slog-kvfilter`. I don't think you're using it, so I don't think that's the same issue.

`TestStdoutWriter` is supposed to be used in tests, so it uses `println!` to allow rust test runner to handle it specially. This is all intentional.

https://github.com/slog-rs/term/blob/088837e0d9e78ae5263f13c3bcf164576fbb8f82/src/lib.rs#L1428

If you think it's misbehaving, please ping us on gitter channel.
