### ISSUE TITLE
Permission denied for logger created in test

### ISSUE THREAD

**Issue by jonathanstrong** [slog-rs/slog#155]
In writing tests for a function that takes a `&Logger` (and clones it) in its signature (and launches some other threads, and does a lot of other complicated things), I cannot find any way to avoid the error below. The error (panic) does not cause the test to fail, but appears interspersed in the output of the test results. 

```
thread '<unnamed>' panicked at 'slog::Fuse Drain: Error { repr: Os { code: 13, message: "Permission denied" } }'
```

I'm using a `Discard` logger created with `Logger::root(Discard, o!())`. 

Any suggestions on possible causes? Can't seem to track down what is happening.

Here's the full stacktrace

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: <slog::Fuse<D> as slog::Drain>::log::{{closure}}
             at /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/sloggers-0.2.4/<panic macros>:7
   8: <core::result::Result<T, E>>::unwrap_or_else
             at /checkout/src/libcore/result.rs:748
   9: <slog::Fuse<D> as slog::Drain>::log
             at /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.1.1/src/lib.rs:1693
  10: <slog_async::AsyncCoreBuilder<D>>::spawn_thread::{{closure}}
             at /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.2.0/lib.rs:253
```

**Comment by dpc** [comment]
I would run the test through `strace` and see which operation returns "Permission denied"

**Comment by jonathanstrong** [comment]
This turned out to be from a logger created by a "downstream" thread that tried to write to a file (and couldn't). But my fundamental error was assuming that `cfg(test)` directives propagate to external crates. The code in question used a `#[cfg(test)]` attribute to disable logging to the file but since it was in an external crate, it didn't trigger when the "calling" crate ran its tests.
