### ISSUE TITLE
Using slog in a library without requiring apps to pass in a Logger

### ISSUE THREAD

**Issue by quodlibetor** [slog-rs/slog#157]
So I've looked at #37 and [the example library](https://github.com/slog-rs/example-lib/blob/master/lib.rs) and it seems like there is no good way for a library to set itself up for logging in the way that the application wants, without requiring that apps thread Loggers through everything.

It seems like, since the `log` crate can handle this, slog ought to be able to manage it as well? I admit that trying to figure out *how* the `log` crate manages it was difficult enough that I gave up, so maybe the complexity means you don't want to support it?

Is this a feature that is desired, is there any thought about what kind of place it deserves on the roadmap?

**Comment by dpc** [comment]
`log` has one global logger, and that's where everything lands.

In your library you can either pass `Logger` everywhere or store `Logger` somewhere and use `slog-scope` to set it up in all API-entry points.

**Comment by quodlibetor** [comment]
So I guess what I would like (from my experience from other systems) is for there to be a global registry of logger sinks, and for the application to configure the drains.

So it's not really the fact that there is a per-library logger, it's that each logger is required to configure its own drains. Would it be possible to either have a single global *registry* of loggers, or to have a default sink that can be hooked up by applications?

Initialization order for a registry might be complicated (or cause performance issues because of lazy_static?), but having a function like `slog::register(lib_name: String) -> Logger` would be nice.

**Comment by dpc** [comment]
@quodlibetor If I understood correctly, this could be easily implemented outside of `slog` core library.

**Comment by dpc** [comment]
I'm closing since, there's nothing actionable here.
