### ISSUE TITLE
Custom Derive

### ISSUE THREAD

**Issue by Michael-F-Bryan** [slog-rs/slog#159]
I've just started using `slog` and so far I'm really, really happy with it! I'm using it on a work project and have found structured logging a lot better than hand-crafted messages where you'll use string formatting to insert information.

One pattern I've started using is to implement `KV` for a struct so I can log its constituent parts. For example I might have a struct like this:

```rust
pub struct Config {
  width: f64,
  height: f64,
  start_point: StartPoint,
}
```

And then (without a `KV` impl) you might log the config details with something like `debug!(logger, "Loaded Config"; "width" => cfg.width, ...);`... Is this a common use case?

I'm thinking of prototyping a custom derive for `KV` in my own repo. If it goes anywhere, would you be interested in adding it to the `slog-rs` organisation?

**Comment by dpc** [comment]
Yes!

We did talk about on the gitter channel, and someone might be working already on it. Please check. :)

**Comment by Michael-F-Bryan** [comment]
Ah okay. I actually made one at work and asked the boss if they're alright with me publishing it, so I was planning to push it to crates.io when I get the okay. 

This is what it looks like at the moment:

```rust
#[macro_use]
extern crate slog_derive;
extern crate slog;
use std::path::PathBuf;

#[derive(KV)]
pub struct Config {
  width: f64,
  height: f64,
  #[slog(skip)]
  output_file: PathBuf,
}
```

**Comment by dpc** [comment]
This is beautiful. Would you like a git repo in `slog-rs` organization?

**Comment by Michael-F-Bryan** [comment]
Yeah, that may be a good idea, I'm sure GitHub has a way to transfer a repository from someone's account into an organisation.

Are there any other custom derives which would be useful when working with `slog`? `SerdeValue` seems easy enough to derive, the two required methods just return a reference and boxed copy, respectively.

**Comment by Michael-F-Bryan** [comment]
Wow, that was a lot easier than expected! It only took about 35 lines of code to write a basic `SerdeValue` impl. Luckily I'm doing this in my own time so I can show you the code :grin: 

```rust
// src/derive_serde_value.rs

use syn::DeriveInput;
use quote::Tokens;
use utils;

pub fn impl_serde_value(ast: DeriveInput) -> Tokens {
    let name = ast.ident;

    let mut tokens = quote!{
        impl ::slog::SerdeValue for #name {
            fn as_serde(&self) -> &::erased_serde::Serialize {
                self
            }
            fn to_sendable(&self) -> Box<::slog::SerdeValue + Send + 'static>  {
                Box::new(self.clone())
            }
        }
    };

    if !utils::contains_named_attr(&ast.attrs, "no_value_impl") {
        let value_impl = quote! {
            impl ::slog::Value for #name {
                fn serialize(&self, _record: &::slog::Record, key: ::slog::Key, ser: &mut ::slog::Serializer) -> ::slog::Result {
                    ser.emit_serde(&key, self)
                }
            }
        };

        tokens.append_all(value_impl);
    }

    tokens
}
```

I'm also using the crate-level docs as tests. Here's the an excerpt showing what I just wrote (written in my own time, so I own the code and can share it) to give you an idea of how the custom derive works.

```
//! # The `SerdeValue` Derive
//!
//! Implementing the [`SerdeValue`] is usually trivial and tedious so it also
//! has a custom derive.
//!
//! ```rust
//! extern crate slog;
//! #[macro_use]
//! extern crate slog_derive;
//! extern crate serde;
//! #[macro_use]
//! extern crate serde_derive;
//! extern crate erased_serde;
//!
//! use std::path::PathBuf;
//!
//! #[derive(Clone, SerdeValue, Serialize, Deserialize)]
//! pub struct Config {
//!   width: f64,
//!   height: f64,
//!   output_file: PathBuf,
//! }
//! # fn main() {}
//! ```
//!
//! This will require enabling `slog`'s `nested-values` feature flag, as well
//! as implementing (or deriving) `serde::Serialize` for your type. You will
//! also need to pull in the [`erased_serde`] crate because it's part of the
//! `SerdeValue` signature.
//!
//! For convenience this will also generate a `Value` impl for your type (to
//! implement `SerdeValue` you must also implement `Value`). This impl simply
//! calls `Serializer::emit_serde()`, but if you want to write your own `Value`
//! implementation you can add the `#[slog(no_value_impl)]` attribute.
//!
//! ```rust
//! extern crate slog;
//! #[macro_use]
//! extern crate slog_derive;
//! extern crate serde;
//! #[macro_use]
//! extern crate serde_derive;
//! extern crate erased_serde;
//!
//! use std::path::PathBuf;
//! use slog::{Key, Record, Serializer, Value};
//!
//! #[derive(Clone, SerdeValue, Serialize)]
//! #[slog(no_value_impl)]
//! pub struct Config {
//!   width: f64,
//!   height: f64,
//!   output_file: PathBuf,
//! }
//!
//! impl Value for Config {
//!     fn serialize(&self, _record: &Record, key: Key, ser: &mut Serializer) -> slog::Result {
//!         unimplemented!()
//!     }
//! }
//! # fn main() {}
//! ```
```

**Comment by dpc** [comment]
I have sent you an invite to a new repo. Please do what you think is best. :)

**Comment by dpc** [comment]
@Michael-F-Bryan Ping? :) Can you push?

**Comment by Michael-F-Bryan** [comment]
@dpc sorry it's taking a while, the guy I was wanting to talk to has been sick. Hopefully I'll be able to get the all clear tomorrow.

**Comment by dpc** [comment]
👍 No worries.

**Comment by Michael-F-Bryan** [comment]
@dpc [pushed](https://docs.rs/slog_derive) :tada:

**Comment by dpc** [comment]
This is pure awesomness! Thank you!

I'm closing this thread since the job was done. I guess `slog_derive` issues can be reoprted in it's repo now: https://github.com/slog-rs/derive/issues
