### ISSUE TITLE
never ever panic ;-) 

### ISSUE THREAD

**Issue by przygienda** [slog-rs/slog#160]
so, I'm not sure it's a panic in any of the packages but I got 

> $<2>Feb 22 ...$<2> thread '<unnamed>' panicked at 'slog::Fuse Drain: Custom { kind: Other, error: StringError("term error: color not supported by the terminal") }', /home/prz/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.1.1/src/lib.rs:1695:33

which is not good. I want an error back so I can e.g. back off to no color drain in my application ... 

we'd need an API that returns the error ...

**Comment by dpc** [comment]
Well, the meaning of `.fuse()`/`Fuse` is to panic on errors. You can write your own error handling/ignore errors.

The `slog-term` has returned an error: https://github.com/slog-rs/term/blob/master/src/lib.rs#L1359 and `Fuse` panicked.

Also, I think in newer `slog-term` version, I've implemented a fallback. So if the terminal is not available for whatever reason (typically docker), `stdio` will be used: https://github.com/slog-rs/term/commit/93587a3533783bdf269b237ca4a441ee7b24f0f7 . Make sure you're using the newest version. :)
