### ISSUE TITLE
"No eval log macro" for hig perf stuff ...

### ISSUE THREAD

**Issue by przygienda** [slog-rs/slog#177]
Looks like 

debug!(...)

does all the eval of args even if behind FilterLevel that kills debug. Major problem for high perf apps. Something like this would be good:

early_filter_debug!(current_level, .... < usual args > )

that does 

if current_level > debug { () } else { log!... }

**Comment by przygienda** [comment]
Benchmarked it, compared to a atomic/level/async stack it's 600ps vs. 26ns so about 50x faster 

suggestion:

```
/// macro to early filter debug!
#[macro_export]
macro_rules! filtered_debug(
	($l:expr, $f:expr, #$tag:expr, $($args:tt)+) => {
		if $f >= slog::Level::Debug {
			slog_log! ( $l, slog::Level::Debug, $tag, $( $args )+ )
		}
	};
	($l:expr, $f:expr, $($args:tt)+) => {
		if $f >= slog::Level::Debug {
			slog_log! ( $l, slog::Level::Debug, "", $( $args ) +)
		}
	};
);
```

**Comment by dpc** [comment]
https://docs.rs/slog/2.3.2/slog/struct.FnValue.html can be used for lazy evaluation.

In slog there is no "one true current level of logging". Each drain has a freedom to process or ignore any message. Compile time static log level is a thing and should get rid of all the debug and trace messages at compile time.

**Comment by przygienda** [comment]
I mean example of the lazy eval ...

**Comment by dpc** [comment]
https://github.com/slog-rs/misc/blob/master/examples/features.rs#L87

**Comment by przygienda** [comment]
ok, I see, it's still too slow for me & not a pretty thought to go and bracket all logs that way but I see how what I suggest is not generic enough ...
