### ISSUE TITLE
Support 2018-style macro imports

### ISSUE THREAD

**Issue by dtolnay** [slog-rs/slog#178]
[This example](https://docs.rs/slog/2.3.2/slog/#logging-to-the-terminal) from the crate-level docs, in 2018:

```ini
[dependencies]
slog = "2.3"
slog-async = "2.3"
slog-term = "2.4"
```

```rust
use slog::{o, Drain};

fn main() {
    let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();

    let _log = slog::Logger::root(drain, o!());
}
```

As of rustc 1.30.0-nightly (33b923fd4 2018-08-18) I receive the following error:

```console
error: cannot find macro `kv!` in this scope
 --> src/main.rs:8:42
  |
8 |     let _log = slog::Logger::root(drain, o!());
  |                                          ^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by dpc** [comment]
I naively thought that: https://github.com/slog-rs/slog/commit/9a14db2d7bbcb7c28c37614d793427951a398dbd would do the job, but there were problem https://github.com/slog-rs/slog/issues/176 and I did not have time to deal with it, so I reverted.

If someone is willing to pick it up and carry the torch, I'm all for it.
