### ISSUE TITLE
Consistent licensing

### ISSUE THREAD

**Issue by gregwebs** [slog-rs/slog#182]
slog itself is triple licensed as MPL-2/Apache/MIT. Other slog projects are just licensed as MPL-2. The async repo is, and most users probably want to use async.

I am hoping that all the slog projects can be provided with the same license. Perhaps this was an intention, but never followed up on?

A question I have that is related to license simplification is: does MPL2 provide any additional license compatibility not available from Apache/MIT?

**Comment by dpc** [comment]
Oh, the licensing.

The answer to most of these questions is I don't know. I think I was told that MPL2 is a good one, and I randomly use MPL-2 or MPL-2/Apache/MIT in most of my open source projects.

If you have any good reason to change `MPL-2` to `MPL-2/Apache/MIT` in any project, please submit a PR, we will ping all the contributors and land it. All fine with me.

**Comment by dpc** [comment]
Now that I've skimmed through some documents I think I liked MPL-2 because it's compatible with GPL and Apache, and is a good compromise between GPL and MIT, that you can't just close the source of "my work", but you're free to use it in "lager work" that can be propriety.

ANAL though.

**Comment by gregwebs** [comment]
Yes, I think many that have used the LGPL would be happy with the MPL. I would like to have consistency across slog projects. Would you like for them to all be licensed as MPL-2/Apache/MIT?

**Comment by dpc** [comment]
Yeah, if you want to do most of the busy-work than I'm fine with `MPL-2/Apache/MIT` for core slog projects.

**Comment by gregwebs** [comment]
After looking at this more closely, most of the newer repos are triple-licensed in Cargo.toml, but just missing LICENSE- files. I created PRs for those:
* https://github.com/slog-rs/term/pull/17
* https://github.com/slog-rs/scope/pull/3
* https://github.com/slog-rs/async/pull/9
* https://github.com/slog-rs/stdlog/pull/7

There are a couple repos that are neither triple licensed or single MPL licensed.
* envlogger: MIT/Apache
* extlog: Apache
* derive: MIT/Apache

MPL only licensed (most of these have not been updated for some time):
* bunyan
* syslog
* json
* extra
* atomic
* config
* stream
* perf
* serde
* cadence
* html
* scope-stdlog
* fmtstream

**Comment by gregwebs** [comment]
Thanks for getting most of those merged already! It seems like Apache is the common license then outside of the MPL batch. I will send a triple-license PR for the MPL libraries where you are the only significant author:

* atomic
* perf
* serde
* scope-stdlog
* fmtstream

**Comment by gregwebs** [comment]
PRs sent for those. Still waiting on [stdlog](https://github.com/slog-rs/stdlog/pull/7) where @robinst was pinged.

**Comment by gregwebs** [comment]
Thanks, I will close this issue and just watch over at the [stdlog PR](https://github.com/slog-rs/stdlog/pull/7) now.

This can be re-opened when someone has a need to re-licene other crates.
