### ISSUE TITLE
Nothing is logged with env RUST_LOG set

### ISSUE THREAD

**Issue by trsh** [slog-rs/slog#198]
If I remove `env::set_var("RUST_LOG", "actix_web=debug,manu=debug");`, error! is logged. Otherwise only file is created.

Versions:

slog = "2.4.1"
slog-stdlog = "3.0.2"
slog-envlogger = "2.1.0"
slog-term = "2.4.0"
slog-scope = "4.0.1"
slog-async = "2.3.0"

Code:

```
env::set_var("RUST_LOG", "actix_web=debug,manu=debug");
  env::set_var("RUST_BACKTRACE", "1");
  //env_logger::init();

  let log_path = "your_log_file_path.log";
  let file = OpenOptions::new()
    .create(true)
    .write(true)
    .truncate(true)
    .open(log_path)
    .unwrap();

  let decorator = slog_term::PlainSyncDecorator::new(file);
  let drain = slog_async::Async::default(slog_envlogger::new(
    slog_term::FullFormat::new(decorator).build().fuse(),
  ));

  let logger = slog::Logger::root(
    drain.fuse(),
    slog_o!("place" =>
           FnValue(move |info| {
               format!("{}:{} {}",
                       info.file(),
                       info.line(),
                       info.module(),
                       )
           })),
  );
  let _guard = slog_scope::set_global_logger(logger);

  slog_stdlog::init().unwrap();

  error!("error");
  info!("info");
  info!("info2");
  debug!("info2");
  trace!("trace");
```

**Comment by dpc** [comment]
Shot in the dark: try using https://docs.rs/slog-async/2.3.0/slog_async/struct.AsyncBuilder.html#method.build_with_guard when building your async guard. Make sure you read documentation https://docs.rs/slog-async/2.3.0/slog_async/struct.AsyncGuard.html .

If it doesn't work still, please put the whole thing (Cargo.toml included) into a git repo/gist and I'll take a look.

**Comment by Phrohdoh** [comment]
There really ought to be an example that covers this specific case, especially since the existing "proper" example [in slog-envlogger](https://github.com/slog-rs/envlogger/blob/e85ac149a51c045cbba28ea8d3b818fe4f7beefa/examples/proper.rs) *does not use* _build_with_guard_.
