### ISSUE TITLE
How to log a strongly typed event in slog?

### ISSUE THREAD

**Issue by U007D** [slog-rs/slog#212]
As per slog-rs gitter channel instructions I am opening an issue.

I've spent a few days looking into slog, but all the examples and documentation appear to be stringly typed.  For my application, I have an `Event` which will get logged, and I would like to understand how I should do this in slog.

Here is the gitter conversation thus far.  **Help/pointers/advice appreciated**!

@U007D Jun 25 13:23
Hi, all, slog newb here. Instead of providing a key value pair to slog via o!("some string" => value), is there a way to provide the kvp via an enum Event { SomeEventWorthLogging(SomeValue) } (via Display trait, Serialize trait or custom .name() and .value() methods)?

@matrixbot Jun 25 20:48
dpc Impl Serialize on the Event
dpc Or impl KV for Event

@U007D Jun 28 04:54
ty, @dpc, will give impl KV for Event a shot

@U007D Jun 28 11:14
@dpc My Event is now impl KV for Event, and I am trying to feed .log() with a &Record.
Record::new() requires a BorrowKV. How can I convert or borrow my Event (which is KV) such that I have a BorrowKV?

@U007D Jun 28 16:15
I'm a bit concerned I may be "doing this the hard way". What I want to do is conceptually straightforward; my [underlying] question is how should I implement something like this? https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b2e26c08496db41bba5512e512f6d3c0

@U007D 07:06
@dpc Any pointers to a non-stringly typed logging example?

**Comment by dpc** [comment]
https://github.com/slog-rs/slog/blob/master/examples/struct-log-self.rs is an example with `impl KV for X`.

Another way is to enable `nested-values` feature and in drains supporting it (`slog-json` mostly), the structure would be serialized as `serde`

**Comment by dpc** [comment]
I think you can also implement `Value` and then `"something" => myvalue` should work.

**Comment by U007D** [comment]
My goal is for the entirety of what is written to the log to be supplied by the type, thus becoming compiler-enforced and avoiding scenarios where a developer accidentally types `"soemthing" => myvalue` (sic) for an event, and suddenly part of our logs are silently invisible to us on query.

After `impl`ementing `KV for Event`, I didn't know where to use Event and got stuck trying to convert it to a `&Record` in order to feed it to `logger.log()`.  For the record, `info!()`, `warn!()` and `error!()` macros will accept an `impl KV`:

```rust
enum Event {
    SomeEvent(u32),
}

impl Event {
    fn key(&self) -> &'static str {
        match self {
            Event::SomeEvent(_) => "SomeEvent",
        }
    }
}

impl KV for Event {
    fn serialize<'a>(&self, record: &Record<'a>, serializer: &mut dyn Serializer) -> SlogResult {
        serializer.emit_str(self.key(), "my value")
    }
}
```

Events can now be fed to info! as `info!(logger, ""; Event::SomeEvent(42));` to yield "Jun 29 12:43:27.464 INFO SomeEvent: my value"

Thank you for the help!

**Comment by dpc** [comment]
Interesting. I didn't really understand your issue.

If you submit an example code, that might help other users, since it seems like a useful technique.
