### ISSUE TITLE
Fix yanked 2.5.1

### ISSUE THREAD

**Issue by CodeSandwich** [slog-rs/slog#219]
Why 2.5.1 was yanked on crates.io? How can it be fixed?

**Comment by dpc** [comment]
Oh, I though you've seen my comment. https://github.com/slog-rs/slog/pull/215/files#diff-b4aea3e418ccdb71239b96952d9cddb6L2186 broke backward compatibility. Previously any prefix of a logging level would get parsed correctly. It was reported on gitter channel.

**Comment by CodeSandwich** [comment]
Hmm, I think I can restore this feature

**Comment by CodeSandwich** [comment]
The issue is fixed. Could you release 2.5.2 to make these changes public?

**Comment by dpc** [comment]
Done. Thanks!
