### ISSUE TITLE
atomic: Use arc-swap instead of ArcCell

### ISSUE THREAD

**Issue by vorner** [slog-rs/slog#222]
Hello

I'd like to ask if it makes sense to use ArcSwap instead of ArcCell inside the slog-atomic. I'd see 3 reasons for that:
* ArcCell is available only in an ancient version of crossbeam, no longer available in newest versions, as it has been deprecated.
* The dependency graph of is not exactly small. ArcSwap has no dependencies.
* ArcCell actually contains a spin-lock, so it may block the caller. Under contention it'll also fight over the reference count in the Arc, making it slower.

If you agree, I'd prepare a pull request of the change.

**Comment by dpc** [comment]
:+1:

**Comment by Techcable** [comment]
It appears this was fixed by slog-rs/atonic#4
