### ISSUE TITLE
The example in slog-atomic contains UB

### ISSUE THREAD

**Issue by vorner** [slog-rs/slog#223]
The example in slog-atomic uses a signal handler. According to posix, using anything but async-signal-safe functions inside a signal handler is undefined behaviour. When reading through the signal handler there, it uses `Box::new` and `Arc::new` inside there. These are heap allocations and these are not async-signal-safe.

Now, as this is just an example, it is not a big deal in itself. But someone could decide to copy it and use it, which would be bad.

Would it be possible to come up with some other example? Should I try creating something?

**Comment by dpc** [comment]
Thanks for pointing this out! Yes, please - if you fill a PR I'd be happy to land it. Anything that is actually correct would do. :D
