### ISSUE TITLE
scope: Update arc-swap to 0.4

### ISSUE THREAD

**Issue by ignatenkobrain** [slog-rs/slog#224]
I would appreciate if you could update `arc-swap` dependency to 0.4: https://github.com/vorner/arc-swap/blob/master/CHANGELOG.md#040

Thanks a lot!

**Comment by dpc** [comment]
In which crate? `slog-atomic`?

**Comment by ignatenkobrain** [comment]
`slog-scope`.

**Comment by dpc** [comment]
PRs, please! :rofl: Thank you!

**Comment by ignatenkobrain** [comment]
Unfortunately I am not experienced enough to do that. I'm just maintainer of `slog-scope` in Fedora.

**Comment by dpc** [comment]
@vorner since you did something similar just now in `-atomic`, what do you think?

**Comment by vorner** [comment]
I can have a look, during the weekend at the latest.

**Comment by metajack** [comment]
Can you publish a new slog-scope, etc now that this is merged?

**Comment by dpc** [comment]
@metajack Done
