### ISSUE TITLE
Exposing slog_term::CompactFormatSerializer & Serializer

### ISSUE THREAD

**Issue by elpiel** [slog-rs/slog#239]
Hello,
In my project I want to change a bit the format(all the logs to start with a `prefix: {message}` or remove timestamp and etc.) of the `CompactFormat`, but without going through all the hassle of reimplementing everything, so I want to copy the `format_compact` and do my changes. The problem is that call of `self.decorator.with_record` uses a closure that calls `CompactFormatSerializer::new` and the struct is private.

The same goes for `Serilizer` as it's called after that.

Want to hear your thoughts :blush:

**Comment by dpc** [comment]
Add `pub` and send a PR. :)

**Comment by elpiel** [comment]
make the correct method public as well + update to edition 2018 if that's ok.

**Comment by dpc** [comment]
Don't bother with 2018. Not much benefit, and it will just bump required version for no benefit.

**Comment by elpiel** [comment]
Just one question, wasn't this already done for travis (bumping the version to 1.32)?
https://github.com/slog-rs/term/commit/5068c81acbdb3536263b1887bc99a257a815f2c8

**Comment by dpc** [comment]
Ehh... I guess someone already did it. :/

People can still write 2015 code, but this will force them to run newer compiler. Not a tragedy, but upgrading minim rustc version for no good reason is unnecessary, IMO.

**Comment by elpiel** [comment]
Sounds good to me. If you want, we can revert back to earlier version of rust in that case.

**Comment by dpc** [comment]
I don't know how much work is it, but please do if it is not too disruptive.

**Comment by elpiel** [comment]
I am not sure what's the exact reason the Rust version was bumped up, but [`term`](https://github.com/slog-rs/term/commit/e639490f4ca4c9bd6201f880ef1f17ba033e9567) was updated and I've checked that this crate is also the 2018 edition.
Is there any benefit of leaving `slog-term` on 2015 then?

**Comment by elpiel** [comment]
Fixed in https://github.com/slog-rs/term/issues/25
