### ISSUE TITLE
Use fully qualified name of Logger::log in macros

### ISSUE THREAD

**Issue by mzabaluev** [slog-rs/slog#240]
The `log!` macro uses the `$l.log(...)` method call syntax to invoke the `Logger::log` method.
This can produce confusing compiler errors in the following situation:

1. A trait is defined that features method named `log`.
2. A generic impl is defined for the trait that, likely by accident, covers `Logger`.
3. slog macros are used in code where the trait is visible, resulting in the trait's `log` method being selected instead of the inherent method of `Logger`.

The solution is to use fully qualified method call syntax in the macros: `$crate::Logger::log($l, ...)`.

**Comment by dpc** [comment]
Fine with me. Please send PR. I wonder how is this going to break stuff. :D
