### ISSUE TITLE
Implement `Clone` for `Never`

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [slog-rs/slog#244]
I totally understand that `Never` is just a stand-in for `!`. However, `!` implements `Clone`: https://doc.rust-lang.org/std/primitive.never.html#implementations

I would like this because currently I have an `slog_atomic::AtomicSwitchCtrl` which has the impl:
```
impl<O: Clone, E: Clone> Clone for AtomicSwitchCtrl<O, E>
```

Another possible fix would be to provide 
```
impl<O: Clone> Clone for AtomicSwitchCtrl<O, Never>
```
but this feels worse to special case something which will go away soon anyway.

Yet another possible fix would be to wrap the `AtomicSwitchCtrl` in an `Arc` but that is just `
Arc<Arc<...>>` which I'd also rather avoid.

I'm happy to make the PR if nobody has any objects, it should just be 1 line.

**Comment by dpc** [comment]
PR please. :)
