### ISSUE TITLE
Support for the {:#} formatter

### ISSUE THREAD

**Issue by netvl** [slog-rs/slog#247]
Right now various macros in slog [support](https://github.com/slog-rs/slog/blob/1af5352de1277800cc48d194c6936144e21f034f/src/lib.rs#L398-L415) the `{}`, `{:?}` and `{:#?}` formatters. However, there are types which also have different format behavior with the `{:#}` formatter, for example, [`anyhow::Error`](https://docs.rs/anyhow/1.0.25/anyhow/struct.Error.html#display-representations):
> When you print an error object using "{}" or to_string(), only the outermost underlying error or context is printed, not any of the lower level causes. This is exactly as if you had called the Display impl of the error from which you constructed your anyhow::Error.
> ```
> Failed to read instrs from ./path/to/instrs.json
> ```
> To print causes as well using anyhow's default formatting of causes, use the alternate selector "{:#}".
> ```
> Failed to read instrs from ./path/to/instrs.json: No such file or directory (os error 2)
> ```

Specifically with `anyhow::Error`, it would be really awesome to have support for the `{:#}` formatter in slog, because it would make printing errors as fields much more readable.

**Comment by dpc** [comment]
I guess adding `#%` couldn't hurt if we already have `#?`. Please fill a PR! :)

**Comment by netvl** [comment]
@dpc #250
