### ISSUE TITLE
Target settings

### ISSUE THREAD

**Issue by mikart143** [slog-rs/slog#270]
Hello!
I am rewriting logging in my app to slog from pretty_env_logger. 
How can I attach target (method name) to slog ? I am using slog_stdlog to keep old libs log.

**Comment by dpc** [comment]
Not sure what do you mean by attach. All the data like this is available in https://docs.rs/slog/2.5.2/slog/struct.Record.html , and if you can add additional dynamic key-values that build from it with https://docs.rs/slog/2.5.2/slog/struct.FnValue.html , or some drains will use it automatically or allow adding some dynamic things that will output it.

**Comment by dpc** [comment]
See #186 maybe for more help.
