### ISSUE TITLE
Logging std::error::Error

### ISSUE THREAD

**Issue by Kixunil** [slog-rs/slog#273]
Currently, it's not specified how to log an error type implementing the `Error` trait. The naive implementation would use `%`, but that's not entirely right as the information about source is lost (`Display` is not supposed to write it).

One could write a helper method to iterate over sources and write them separated with `: `. This works but the structural information is lost. I believe that error types are something one would very much desire to log (at least that's what I do), so it'd be nice to provide a better support for it.

I propose to add a new method to the `Serializer` called `emit_error()` that will accept any type implementing `std::error::Error` and by default iterates through sources and writes them separated by `: `.

I also propose adding a new modifier, e.g `#` for the macros that will log an error using this method.

**Comment by dpc** [comment]
I guess I'm fine with it, but please double check if adding `#` is really, really, really backward compat.
