### ISSUE TITLE
[Question] Reconfiguring global logger?

### ISSUE THREAD

**Issue by Geobert** [slog-rs/slog#278]
Hi,
I have a global logger via slog_scope::set_global_logger and kept its guard. Now I want to reconfigure this logger.
I tried to drop the guard and recreate another global logger, but I get a panic when dropping the guard…
Is that normal? according to slog-rs/slog#169 it seems so but then…

 how should I reconfigure the global logger?

**Comment by dpc** [comment]
Yeah, you're not supposed to drop that logger. You might want to use `slog-atomic` as a global logger, which should allow you to switch it atomically at any time.

**Comment by Geobert** [comment]
Thank you!
