### ISSUE TITLE
update slog-term to use newer term?

### ISSUE THREAD

**Issue by Kixunil** [slog-rs/slog#279]
I would've opened a PR but the new version of `term` (7.0) bumps MSRV to 1.36.0 which would break MSRV of `slog-term` (I guess, I saw 1.32.0 in `.travis.yml`).

So I'm asking: should it be updated? If not how to avoid stagnation and duplication of dependencies?

**Comment by dpc** [comment]
Seems like 1.36 will be 2yo in July. I guess we could do it, bumping the minor version.

**Comment by Kixunil** [comment]
Opened https://github.com/slog-rs/term/pull/35
