### ISSUE TITLE
Unconsistent slog::Level conversion to string on Warning variation

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [slog-rs/slog#282]
`slog::Level::Warning.as_str()` results in the same `WARN` as `slog::Level::Warning.as_short_str()` instead of the `WARNING` one might expect. Is this intentional in anyway?

The related source:
https://github.com/slog-rs/slog/blob/f9e30f0dd9bad610227d9374001fcc13d5b7c8c8/src/lib.rs#L2076-L2086

Where variants like `Critical` are `CRITICAL` and `CRIT` on the str representation.

**Comment by dpc** [comment]
Probably not. Weird that no one ever raised it.

**Comment by pravic** [comment]
Interestingly enough, [log](https://docs.rs/log/latest/log/enum.Level.html#method.as_str) also uses `WARN`: https://docs.rs/log/0.4.20/src/log/lib.rs.html#414.
