### ISSUE TITLE
[Feature] notice log level

### ISSUE THREAD

**Issue by tetraf** [slog-rs/slog#287]
Sometimes I need to display important information in log that are not a warning but a bit more than an info!(). A notice!() level seems to be nice for that.

**Comment by dpc** [comment]
I doubt it's gong to happen for backward compatibility and compatibility with `log` reasons mostly.

BTW, I generally find logging levels a flawed concept, confusing developers. I'd rather have a list of tags to filter on, rather than just levels. But it is what it is, so oh well.
