### ISSUE TITLE
ErrorValue requires the wrapped error to be 'static

### ISSUE THREAD

**Issue by lilyball** [slog-rs/slog#288]
The `ErrorValue` type wraps any `E: std::error::Error` to allow logging of the error and its source chain. But it requires `E` to also be `'static` (as does `Serializer::emit_error`). There's no requirement for this bound, I can rewrite `ErrorValue` myself to work without it, so slog should get rid of it too.

**Comment by dpc** [comment]
My lifetime-fu got rusty, but it might be that for object-safety, `emit_error` needs an explicit lifetime - `'static`.

**Comment by lilyball** [comment]
I made my own ErrorValue-like type that basically inlined the call to emit_error and used a `'a` lifetime on its impl instead of `'static` and that worked just fine.

**Comment by dpc** [comment]
Worked fine for what exactly?

**Comment by lilyball** [comment]
I was able to log the error using `"error" => MyErrorValue(&e)`. There's no reason the real `ErrorValue` type can't work the same way.
