### ISSUE TITLE
Consider opening Github Discussions

### ISSUE THREAD

**Issue by Techcable** [slog-rs/slog#298]
Might be a better fit for questions and long-form discussions than the gitter (which seems relatively inactive).

I often don't have time to check Gitter but I could definitely respond to discussions more quickly.

**Comment by dpc** [comment]
I haven't looked them a lot yet, but Discussions seem very promising and I'd prefer to use them as well.

**Comment by dpc** [comment]
https://github.com/slog-rs/slog/discussions/299
