### ISSUE TITLE
Cleanup `slog-envlogger` comments.

### ISSUE THREAD

**Issue by dpc** [slog-rs/slog#32]
Since I forked original `env_logger` (whole `log` github repo, where it was), I left a lot of documentation as it was originally. This might be confusing. It's a bit of manual labor, that needs to be taken care of.

https://github.com/dpc/slog-envlogger

**Comment by andreastt** [comment]
The link from the the main repo (https://github.com/slog-rs/slog) seems to work now. Previously it lead you to a blank document.

**Comment by dpc** [comment]
No progress, not sure if it's worth it.
