### ISSUE TITLE
puzzling apparent conflict between slog, env_logger

### ISSUE THREAD

**Issue by jonathanstrong** [slog-rs/slog#320]
I came across some puzzling behavior, where changing the order of a few lines when constructing the `Logger` in `fn main` can either work fine or cause major bugs.

this is a code snippet to illustrate the problem as simply as I can. there are three `fn main`s in example, the top one is causing problems and the bottom two (slight changes to order of operations) work fine. 

```rust
#[macro_use]
extern crate slog;

use slog::Drain;

fn stdout_logger() -> slog::Logger {
    let decorator = slog_term::TermDecorator::new()
        .stdout()
        .build();
    let drain = slog_term::CompactFormat::new(decorator)
        .build()
        .fuse();
    let drain = slog_async::Async::new(drain)
        .chan_size(1024 * 64)
        .thread_name("my-logger".into())
        .build()
        .fuse();
    slog::Logger::root(drain, o!("version" => env!("CARGO_PKG_VERSION")))
}

// this one causes baffling behavior, including failures that are beyond just
// logging-related problems, ie function that is working in the other examples
// returns an error in this version instead.
fn main() {
    let logger = stdout_logger();
    let env_logger = env_logger::Logger::from_env(env_logger::Env::new().default_filter_or("debug"));
    rustwide::logging::init_with(env_logger);
    // ..
}

// this one works fine (emit a `debug!` log prior to the env_logger stuff)
fn main() {
    let logger = stdout_logger();
    debug!(logger, "initializing ...");
    let env_logger = env_logger::Logger::from_env(env_logger::Env::new().default_filter_or("debug"));
    rustwide::logging::init_with(env_logger);
    // ..
}

// this one also works fine (`logger` constructed following the env_logger stuff)
fn main() {
    let env_logger = env_logger::Logger::from_env(env_logger::Env::new().default_filter_or("debug"));
    rustwide::logging::init_with(env_logger);
    let logger = stdout_logger();
    // ..
}
```

Unfortunately, tracking and explaining what happens is somewhat complicated - this is a big program with tons going on in many threads. Also the behavior of the buggy version is very confusing. Not only do the logs not show up (which makes diagnosing what happened super difficult!), but the program also fails in terms of its non-logging-related output. i.e. a function that returns `Ok(_)` in the working versions returns `Err(_)` in the buggy one. 

The part of the program that fails is on another thread from where the `logger` was originally constructed, also it is using a `tokio` runtime (which was constructed on the other thread), so there are possible `async`/`tokio` issues in play. 

It likely occurs in a section of code where `rustwide` is actively capturing logs, but I don't know for sure (since I don't get any logs). 

I get the same behavior with debug and release builds.

The `rustwide::logging::init_with` function is [here](https://github.com/rust-lang/rustwide/blob/ad5e792ccd19d04e1e1d013c83ddd4ca167365ed/src/logging.rs). I haven't looked closely at what is going on there, but the code in that file is used to capture logs during sandboxed rust builds.

The reason I have both `slog` logger and the env_logger is because my code uses `slog` but some of the libraries are generating logs other ways that I would like to be able to view/capture.

do you guys have any kind of hypothetical theory for what might be behind this behavior? I am mostly interested in ensuring it doesn't happen (i.e. avoiding the buggy version). Seems this could possibly be the combination of overlapping global or thread local static values used to store state and macros that could paper-over type compatibility problems, but that's only a stab in the dark.

**Comment by dpc** [comment]
Hard to say. My instincts tell me: some circular initialization / locking, triggered in one of the lazy-initialization code.

**Comment by Techcable** [comment]
I will look into this when I have time. Definitely concerning 😦

**Comment by jonathanstrong** [comment]
Closing this issue as the problem turned out to be wholly unrelated to slog. Apologies for a false alarm.
