### ISSUE TITLE
slog-json only outputs level in short form

### ISSUE THREAD

**Issue by joacohoyos** [slog-rs/slog#324]
It seems that when using slog-json the log levels are printed in their short form.

If I check the code it seems like it's using as_short_str by default without a way to configure it.
Would be nice to add a config on the constructor to be able to chose which one to use or default to the long name.

https://github.com/slog-rs/json/blob/master/src/lib.rs#L340

**Comment by dpc** [comment]
I vaguely remember that this is entirely possible, by skipping default formatter and defining your own, BTW.

**Comment by joacohoyos** [comment]
> I vaguely remember that this is entirely possible, by skipping default formatter and defining your own, BTW.

Yeah you are right, didn't though of going that route
