### ISSUE TITLE
formatting without key/values doesn't work on some expressions

### ISSUE THREAD

**Issue by scottlamb** [slog-rs/slog#74]
The crate-level doc says that slog supports formatting, with or without a preceding `"key" => "value"`. But there's at least one annoying caveat.

This compiles and works:

```rust
info!(self.log, "foo" => "bar"; "wrote recording {}", r.sample_file_uuid.hyphenated());
```

but without the key/value prefix, it fails with slog 1.1.0 and rustc 1.14.0-nightly (6dc035ed9 2016-10-15):

```
error: no rules expected the token `.`
   --> src/streamer.rs:136:48
    |
136 |         info!(self.log, "wrote recording {}", r.sample_file_uuid.hyphenated());
    |                                                ^
```

Looks like I can wrap the expression in ()s and have it work again but that's ugly. I haven't played with Rust macros much but it seems like this should be fixable.

**Comment by dpc** [comment]
Oh. I think that should be fixable. Thanks for reporting it!

**Comment by dpc** [comment]
I can't reproduce. I have no idea why. Any way you could write a standalone version?

**Comment by dpc** [comment]
OK. I reproduced. :)

**Comment by dpc** [comment]
Please review the PR.
