### ISSUE TITLE
support any value implementing Display/Debug

### ISSUE THREAD

**Issue by scottlamb** [slog-rs/slog#75]
I'd like to be able to just do this on `uuid::Uuid`:

```rust
info!(self.log, "wrote recording"; "uuid" => r.sample_file_uuid.hyphenated());
```

but it fails with these errors:

```
error[E0277]: the trait bound `for<'c, 'd> uuid::Hyphenated<'_>: core::ops::Fn<(&'c slog::Record<'d>,)>` is not satisfied
   --> src/streamer.rs:136:9
    |
136 |         info!(self.log, "wrote recording"; "uuid" => r.sample_file_uuid.hyphenated());
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trait `for<'c, 'd> uuid::Hyphenated<'_>: core::ops::Fn<(&'c slog::Record<'d>,)>` not satisfied
    |
    = note: required because of the requirements on the impl of `slog::Serialize` for `uuid::Hyphenated<'_>`
    = note: required for the cast to the object type `slog::Serialize`
    = note: this error originates in a macro outside of the current crate

error[E0277]: the trait bound `for<'c, 'd> uuid::Hyphenated<'_>: core::ops::FnOnce<(&'c slog::Record<'d>,)>` is not satisfied
   --> src/streamer.rs:136:9
    |
136 |         info!(self.log, "wrote recording"; "uuid" => r.sample_file_uuid.hyphenated());
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trait `for<'c, 'd> uuid::Hyphenated<'_>: core::ops::FnOnce<(&'c slog::Record<'d>,)>` not satisfied
    |
    = note: required because of the requirements on the impl of `slog::Serialize` for `uuid::Hyphenated<'_>`
    = note: required for the cast to the object type `slog::Serialize`
    = note: this error originates in a macro outside of the current crate
```

Why not have a default implementation of `slog::Serialize` based on the `Display`/`Debug`/`ToString` traits?

As is, I think I have to add a `.to_string()` myself:

```rust
        info!(self.log, "wrote recording"; "uuid" => r.sample_file_uuid.hyphenated().to_string());
```

which is annoying. I imagine it's also not as efficient as it could be. I don't know the details of slog's implementation, but I'd expect a Display-based implementation could format the thing into a single buffer for the whole log message rather than require me to create a separate allocation for each value. In fact, I think from skimming the log macro that it's checking the compile-time max log level (`__slog_static_max_level()`) before calling this code, so I'd have to actually do this to avoid the allocation:

```rust
info!(self.log, "wrote recording"; "uuid" => |_: &slog::Record| r.sample_file_uuid.hyphenated().to_string());
```

which is unreadable.

I was able to create a generic wrapper:

```rust
struct L<'a, T: 'a + fmt::Display>(&'a T);

impl<'a, T: 'a + fmt::Display> slog::Serialize for L<'a, T> {
    fn serialize(&self, _: &slog::Record, key: &str, s: &mut slog::Serializer)
                 -> Result<(), slog::ser::Error> {
        s.emit_arguments(key, &format_args!("{}", self.0))
    }
}
```

which allowed me to do this:

```rust
info!(self.log, "wrote recording"; "uuid" => L(&r.sample_file_uuid.hyphenated()));
```

but I'd prefer not to have to wrap everything in `L(&...)`.

**Comment by dpc** [comment]
The `Display` can't be used as different Serializers can serialize different types in different way. Eg. in json, numbers and strings are different.

Would

```
info!(self.log, "wrote recording"; "uuid" => format_args!(r.sample_file_uuid.hyphenated()));
```

work for you? `Arguments` implements `Serialize` and it does not allocate until actually formatted.

**Comment by dpc** [comment]
Another workaround would be to use a macro. That has a benefit of being able to get rid of `hyphenated()` too.

You could have eg.:

```
info!(self.log, "wrote recording"; uuid!(r.sample_file_uuid));
```

**Comment by dpc** [comment]
Other than helping with a workaround suggestion, I don't think I can change this fundamentally.

**Comment by scottlamb** [comment]
Yeah, either the format_args! or the new uuid! macro would work but as far as aesthetics/readability go I'd prefer the simple code just work.

I see what you mean though about the conflicts. I just tried sticking this into ser.rs:

```rust
impl<T> Serialize for T where T: fmt::Display {
    fn serialize(&self, record: &Record, key: &str, serializer: &mut Serializer)
                 -> result::Result<(), Error> {
        serializer.emit_arguments(key, &format_args!("{}", self))
    }
}
```

and it conflicts with the `impl Serialize for ()`. Shoot.

**Comment by dpc** [comment]
Well, I can't help you much so, I'm going to close. Feel free to re-open and join the gitter to discuss ideas. I'd personally go with a macro + `format_args` - easy to implement, makes the code shorter anyway. You could also create a new child instance of `Logger` in case you keep repeating that `uuid` field.
