### ISSUE TITLE
Readme should have a minimal "Getting Started" section

### ISSUE THREAD

**Issue by LaylConway** [slog-rs/slog#82]
To get people quickly going with a library, it's useful to have a very minimal getting started section as the first or second thing visible on the readme. This way people don't have to hunt around trying to find the simplest example to get going.

**Comment by dpc** [comment]
That's true. I'll keep it open.

**Comment by dpc** [comment]
How about now? What do you think?

**Comment by LaylConway** [comment]
Looks good, this will certainly help people get slog up and running much easier

**Comment by dpc** [comment]
Would be nice to have something more elaborated, but that as much as I can realistically invest in it at this point. :)
