### ISSUE TITLE
Missing length parameter for SerdeSerializer::start(...)

### ISSUE THREAD

**Issue by emallson** [slog-rs/slog#85]
For the JSON formatter (`slog_json`) this isn't necessary. However, some Serde-based formatters do need it.

My particular use-case is MessagePack, which [requires the length for a map](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-map). This is carried forward to the [serde implementation of messagepack](https://docs.rs/rmp-serde/0.10.0/src/rmp_serde/.cargo/registry/src/github.com-1ecc6299db9ec823/rmp-serde-0.10.0/src/encode.rs.html#352-362), which requires a non-`None` length parameter.

However, since the `start` function on `SerdeSerializer` assumes that the length is `None`, it is impossible to use it with certain Serde formatters.

This appears to be a pretty easy change to make, though it'd be breaking for any package using `::start` directly instead of something like `slog-json`.

**Comment by dpc** [comment]
I'm glad to hear you are investigating `msgpack` support. `slog-serde` is not `1.0.0` yet, so breaking it is not a problem. Feel free to hack on it and submit a PR. Also if you'd like make `slog-msgpack` crate I can create a repo in `slog` community and make you and admin.

**Comment by emallson** [comment]
Just submitted the PR. I'm not ready to make a slog-msgpack crate yet, but assuming I continue using it I may consider doing so. (I temporarily switched to gzipped JSON because that already worked with slog, and not sure whether there will be a meaningful size difference that warrants switching back to msgpack).

**Comment by emallson** [comment]
The `slog-rmp` code is [here](https://github.com/emallson/slog-rmp). As mentioned in the README for it, it is very very rudimentary and I am not currently planning to maintain it.

You may also consider moving most of the code for `slog-json` into `slog-serde` and then making `slog-json` a very thin wrapper around it. This is because the only function that uses the `SerdeSerializer` is `format`, so you could have e.g.

```rust
let rmp_drain = slog_stream::stream(file, SerdeSerializer::new::<rmp_serde::Serializer>());
let json_drain = slog_stream::stream(file2, SerdeSerializer::new::<serde_json::Serializer>());
```

I may play around with this and submit another PR when I get the chance.
