### ISSUE TITLE
Custom serialisation?

### ISSUE THREAD

**Issue by alexreg** [slog-rs/slog#87]
Is there any reason why you implement your own serialisation framework, effectively, rather than using *serde*?

**Comment by dpc** [comment]
Couple of reasons.

* `serde` is not yet `1.0`
* I wanted to narrow down the supported types. Each `Drain` will have to support every type, and I wasn't sure if requiring them to support collections is the best idea.
* `serde`'s is not meant to serialize key-value pairs only; it can do that, but it doesn't map exactly precisely
* maybe I didn't know better :)

**Comment by alexreg** [comment]
Fair points. I might counter be saying: serde is very mature and stable nonetheless; you could return not-implemented errors for unsupported types. But I won't argue, since your decisions seem reasonable enough. Just wanted to make sure you were aware. :-)

**Comment by dpc** [comment]
In couple of years, when Rust and slog get more popular, there might be a time to revise some design decisions, and release `slog 2.0` with `slog 1.0` backward-compatibility of some kind. :)

Closing for now, feel free to chat/reopen as needed.

**Comment by Emilgardis** [comment]
Why would someone need 1.0 backward-compatibility?

**Comment by dpc** [comment]
To eg. be able to use any libraries that still link to `slog` 1.0.
