### ISSUE TITLE
Expose __slog_static_max_level with a nice API

### ISSUE THREAD

**Issue by Drakulix** [slog-rs/slog#88]
`__slog_static_max_level()` would be very useful to wrap calculations for logged objects, that might not be needed, if no values are actually logged at the current active log level.

Of course you may work around that:
```
debug!("{:?}", {
    mystruct.some_expensive_calculations();
    mystruct.some_more_calculations();
    mystruct
});
```

But this might not always be convenient.
`__slog_static_max_level()` itself is not a particulary nice function to use, so I propose some new macros:
```
debug_enabled!({
    mystruct.some_expensive_calculations();
    mystruct.some_more_calculations();
});
...
debug!("{:?}", mystruct);
```
Or some functions:
```
if slog::debug_enabled() {
    mystruct.some_expensive_calculations();
    mystruct.some_more_calculations();
}
...
debug!("{:?}", mystruct);
```

This would of course open the possibility (like intentionally shown) to have side effects depending on logging, which is usually not recommend, so I understand, if you are not interested in implementing this functionality.

However there are some valid usecases for this and it is currently already possible as shown at the beginning, just unnecessarily limited. 

Nice project btw.

**Comment by dpc** [comment]
It definitely makes sense. I initially like the function versions better since it feels more natural and avoids macros, but would have to give it at least a day of thought to settle :). If you feel like submitting a PR, please do.

**Comment by Drakulix** [comment]
> If you feel like submitting a PR, please do.
I do, but it might take some days, since my time is quite limited currently.

**Comment by dpc** [comment]
Same here. No worries. :)

**Comment by dpc** [comment]
Some thoughts on this one: There are two or more logging levels: one is static one, global for all the build, and another one - dynamic once, that is specified in the drain composition itself. And there can be more than one of such levels. Because of that, I think having anything like `debug_enabled()` will be confusing.

**Comment by dpc** [comment]
As a workaround, I'd say that anything can implement `slog::ser::Serializable` so you can implement it for `MyStruct` and that "hard work" can be done only if `MyStruct` actually get serialized.

**Comment by dpc** [comment]
I'm closing but feel free to reopen.
