### ISSUE TITLE
Rename `o` macro

### ISSUE THREAD

**Issue by alexreg** [slog-rs/slog#89]
Since macro names aren't namespaced, and can clash, this is too short/common a name for a library to be using, I feel. Maybe it could be `slog_o` or `slogo` though. :-)

**Comment by dpc** [comment]
I guess `slog_o` as a backup alternative name, wouldn't hurt. :) :+1:

**Comment by dpc** [comment]
Done.

**Comment by alexreg** [comment]
Thanks!
