### ISSUE TITLE
TAG-based filtering between components

### ISSUE THREAD

**Issue by przygienda** [slog-rs/slog#92]
Trying to figure out how to have a main logger that is passed down into components that based on their configuration set a LevelFilter. I can't get the drain from the drain from main log for LevelFilter::new and I don't want a new logger but the previous logger copied (but it doesn't take LevelFilter as Drain, only root does) ...

**Comment by przygienda** [comment]
Kind of came to conclusion that I need to derive a custom LevelFilter that does the filtering as a drain ...

**Comment by dpc** [comment]
I'm not sure what `derive` means. All you want is `Filter` (https://docs.rs/slog/1.3.2/slog/struct.Filter.html), it seems. In this filter you want to distinguish which component are you logging from (by inspecting `Record`) and deciding if given logging record should pass or not.

**Comment by przygienda** [comment]
Sigh, and that doesn't work. In simplest terms I try to filter on something which is in the values on the record but there is nothing like this around. 

a) Filter does get passed values inside but there is no way to "parametrize" it as to which values on which keys I want to filter
b) even if, the values are wrapped into serializer which makes it impossible to get the real "values" to compare against, you can only "emit" them. 

In short, looks to me like the slog has a serious shortcoming, I cannot e.g. flip the filter per thread if I have the thread_id in values since I cannot filter on values. Looks like I have to construct a drain _per_ thread then log to it which of course ruins the main property of slog, namely drain serialization (I would ideally like a single sterm drain of course but can't find a design for it with the architecture of slog). Sigh ...

**Comment by przygienda** [comment]
It is quite common to filter on large systems of whole slew of properties which are orthogonal to the code structure, e.g. I may mark everything that has to do with sending packets with o!("sender" => true) and use that to switch on packet sending code across the code. Same for threads, same for e.g. FSMs ... This would precondition a filter that can look @ values (value hidden in serializer currently) ...

**Comment by dpc** [comment]
It is possible to iterate over all values, find the key you're interested in, emit it to your own `Serializer` and check the value.

**Comment by przygienda** [comment]
Thanks. Sigh, how do I build a serializer like this, do I have to alloc a serializer, store on emit into a string I can read, then reset it (kind of like a Cursor?) ... That's helluva of work & not a great design. Probably will be a pretty slow dog. I assume @ least the id() stays stable so I could build a "hashing serializer" with a cache hashed on id() ?

**Comment by dpc** [comment]
So I see the problem now that closure passed to filter does not take `logger_values: &OwnedKeyValueList`, like every drain does: https://docs.rs/slog/1.3.0/slog/trait.Drain.html#tymethod.log . So you can't use `Filter` but you have to write your own structure implementing `Drain` that is similar.


You'll have to iterate through `OwnedKeyValueList` with https://docs.rs/slog/1.3.0/slog/struct.OwnedKeyValueList.html#method.iter which yields elements of type https://docs.rs/slog/1.3.0/slog/type.OwnedKeyValue.html. Siince this list it's ordered in the same order the keys were added, if you add your "tags" early, you'll always find them quickly when iterating. String comparison of the key should be quick.

Now `Serializer` is just a struct that implements `Serializer`. You just write your own, and on every `Drain::log` create one (on stack, no allocation needed), and make it parse the value of the key you needd, and return a value for you. Something like:

```
enum Tag {
 A,
 B
}

struct MyTagSerializer {
   tag : Option<Tag>,
}

impl Serializer for MyTagSerializer
    fn emit_str(&mut self, key: &'static str, val: &str) -> ser::Result {
        if val == "A" {
             self.tag = Some(Tag::A)
         } else if val = "B" {
             self.tag = Some(Tag::B)
        }

        Ok(())
}

impl MyTagSerializer {
    fn into_tag(self) -> Option<Tag> {
          self.tag
    }
}
````

**Comment by dpc** [comment]
BTW. It's usually good to ping me on github, if you'd like faster response. I'm quite confident that your requirements can be satisfied and the performance will be good. Even if all these parsing and stuff would be slow for any reason, you can offload it to another thread with `slog_extra::Async`.

As you originally (in the title) asked for better documentation - it's impossible for me to write even a short tutorial for every possible scenario. I can't even imagine every possible scenario. I just made slog general and flexible enough that I hope it will be able to deal with 99% scenarios. Anyway, I would always appreciate a short blogpost and something like that describing what you did with slog, so people can google it, and it can be posted on r/rust and stuff. Feel free to ping me if you get stuck with anything.

**Comment by przygienda** [comment]
yeah, agree, design-wise ugly beast a bit (i.e. generating a serializer _per_ value you want to look at. I aim @ something that is a single serializer and does per (&key, usize) store the value (since I have to walk the whole thing recursively, one tag may be @ root, the other in another log copy deeper). 

I suggest for next release to consider something that 

a) allows to look @ value formatted out from a OwnedKeyValue 
b) something that allows to get the list of values recursively up the chain for a Key 
c) something that allows  values_for(key).in_filtervalues(parameter) 

I'll ping you on github ...

**Comment by przygienda** [comment]
I see you in Santa Clara, I assume you work for one of the big shops ;-) 

There are couple of Polish guys around and independently if you want a chat in Polish, let's grab a beer ;-) I'm in Sunnyvale, prz@zeta2.ch is good or you find me on Rust channel in mozilla as prz ...

**Comment by przygienda** [comment]
OK, implemented it. If anyone is interested in folding that into next release, I can contribute. It's basically a special filter that looks like this 

        // build some small filter
        let filter = AttributeValuesFilter::new(drain,
                                                HashMap::from_iter(vec![("thread".to_string(),
                      HashSet::from_iter(vec!["100".to_string(), "200".to_string()])),
            ("direction".to_string(),
                HashSet::from_iter(vec!["send".to_string(), "receive".to_string()]))]));

        // Get a root logger that will log into a given drain.
        let mainlog = Logger::root(filter.fuse(),
                                   o!("version" => env!("CARGO_PKG_VERSION")));

and will filter using the Borrowed _and_ Owned hierarchy correctly. I have a cache for the OwnedValues so inheriting loggers should be very cheap. Borrowed needs a lookup every time the OwnedValues didn't pass the filter ... 

Opinion ?

**Comment by dpc** [comment]
> generating a serializer per value you want to look at

If written right nothing is really "generated". Everything happens in-line, on stack and should be efficient. The code might not look pretties, but can be just wrapped in one function. 

> I suggest for next release to consider something that (...)

I don't fully understand, but from what I can understand I don't think it will work. The things are the way they are to make the common case extra-fast. Anything more sophisticated will have to pay some price, but I think it's the right tradeoff.

> It's basically a special filter that looks like this (...)

I don't fully understand. I'd have to look at the full source. If it's available I could check it and maybe help to optimize if possible.

> If anyone is interested in folding that into next release, I can contribute. 

The way things are envisioned, the core `slog` crate is and will be very small. You don't have to wait for slog release - you can just put this `Drain` into separate crate ("slog-tags"? or something like it), and people can reuse your code. I think it would be an interesting addition.

**Comment by przygienda** [comment]
Dawid, lemme throw the code up so you see what I did. Yepp, non-optimal, worst problem is I ended up copying Strings all over the place since couldn't come to terms with the lifetimes ... 

<script src="https://gist.github.com/przygienda/f7386a432c876988f35f7e05bfc0c0b3.js"></script>

Check out whether that's of interest and if yes, I can polish that over time up for general consumption ... 

Separate crate is fine albeit I saw comments you want to unify filters in slog.

**Comment by dpc** [comment]
@przygienda It looks to me that you achieved what you wanted. `Serializer` is OK. I'm puzzled why there was a need for cache, `HashMap`, `Mutex`, and so on. Seems to me it should be based mostly on quick linear search.

The way I'd see a generic, reusable component like that would be something like:

```
//! crate: slog-rulefilter

/// A filter deciding to log (or not) a given `Record`
trait Filter {
     /// Should given `Record` be logged into corresponding `Drain`
     ///
     /// `key` is the key that triggered the `Filter` and `val` is the associated value
     fn should_log(&self, info: &Record, logger_values: &OwnedKeyValueList, key : &'static str, val :  &Serialize`) -> bool;
}

/// A filtering Rule
struct Rule {
    /// Key name triggering rule
    key : &'static str,
    /// Filter, deciding should a given `Record` be logged or not
    filter : Box<Filter>,
    /// Drain to log if `filter` passed
    drain : Box<slog::Drain>
}

/// A Filter that runs logging `Record`s through series of rules
struct RuleFilter {
    rules : Vec<Rule>,
}

impl Drain for RuleFilter { ... }
```

If there was to be a lot of `Rule`s,  `RuleFIter::rules` could be a `HashMap<Vec<Rule>>`

**Comment by przygienda** [comment]
Hey, well, imagine something running a dozen log levels (I'm @ 6 already), each of them tagged differently so I can do something like this 

level1 = {a,b} level2 = {c,d} ...

and so on. On every log I hit I owuld have to go recursively up & collect all the stuff (that's what I'm caching). Performance would be unbearable. 

Yeah, I got it working to my liking albeit having exposed the value without serialization would have made my job significantly simpler ... 

So, you think I should publish that as indpendent thing to slog ? Or we fold that into the Filter after you generalize the logLevelFilter into specialization of something more generic?

**Comment by dpc** [comment]
I still don't get it. What does `level1 = {a,b} level2 = {c,d} ...` mean exactly?

Core `slog` needs to work with `#[no_std]` so definitely not there. I think separate crate is a best way to start, since you have complete freedom (eg. to break API).

**Comment by przygienda** [comment]
OK, updated the filter (found a subtle recursive bug). Under 

here's the new gist  https://gist.github.com/przygienda/f7386a432c876988f35f7e05bfc0c0b3

**Comment by przygienda** [comment]
Oh, I see why the API is unclear, need to polish the docu. 

It's basically hashmap<KEYWORD, hashset<possible values >>

anything that matches all keywords it carries on any possible value will be shown (fully recursive and with specific slog(..., ..) values if you look @ the test. 

Works very well with 140 threads pumping data like crazy here.

**Comment by dpc** [comment]
OK. So I think I finally understand. It's definitely the most interesting `Drain` implementation so far.

Couple of points:

* `id()` that you're using for caching is currently buggy (explained in #90). I was planing to remove it, but your use case suggest to me that it might be actually really needed. It can be made reliable, but it costs an atomic increment and assignment for every `Logger` instance, so I was reluctant to add it. Now I think I'm going to put it behind a feature flag, so crates like this one can turn it on, and only then a user will pay (tiny but still) performance price for it. The fundamental problem with it is it does not work with closures since the value returned by closer can change every time the same logging statement is being called. But I guess in this case it does not matter, and that caching using id is saving a lot of time.
* The `cache` should ultimately be turned into some form of LRU, otherwise it's theoretically unbounded.
* `key` is redundant? `filters` already has everything. One can iterate with `HashMap::keys()` and check if key exists with `HashMap::contains_key`.
* I think there's a room for cleanup and more idiomatic code.
* I think there's a room for speedup here and there. `ToStringSerializer` does not have to allocate a string every time, and can reuse a thread-local one, some `clone` could be removed and maybe there's a way to not have to allocate all these temporary datastructures on cache miss. I guess the cache hits on `id` is eventually taking care of everything for your, but it might make a difference if it becomes an LRU.
* I was wondering if the design could be easily altered to take multiple `Box<Drain>`s to decide where to log a given record. It's more general, and after all that work to match keys and values it would be nice not have to repeat it for another sub-drain. But it's perfectly fine to not do it, if it increases complexity or lower performance.

I think we should agree on the crate name, I could create a repo for it under slog-rs github organization and give you all the rights or take over the code - as you wish. You can push it there, and I can submit PRs that you can review.

"Attribute" is not something used in slog nomenclature, though it probably makes sense from the perspective of what you're building. Instead "key-value" is used everywhere in slog. 
I'm thinking about `KVFilter` struct and `slog-kvfilter` crate (kv for "key-value").

**Comment by przygienda** [comment]
Hey Dawid, all sounds good and the observation of id() is good. I can live for the moment with dropped messages if ID's misfire or messages passing falsely. 

Drop a crate on me & I'll start working on that. On the idomatic cleanup I may need some help, I'm only 6 months into Rust and old hands reviewing can surely teach me a bunch. 

The unit test is ugly with the globals but Drain is so well encapsulated I didn't see a simple solution off the bat to oipen a channel and get this info back somehow ...

**Comment by dpc** [comment]
Oh. And `id()` is per Logger-assigned values. So caching should be done not on `id()` but on `id() + record.module + record.line` or something like that. Even if `id()` is fixed.

**Comment by dpc** [comment]
I actually need some time to fully digest the issue and come with best solution.

**Comment by dpc** [comment]
@przygienda Do you think it would be OK to make the order of keys to match significant? Right now:

```
pub type FilteringMap = HashMap<String, HashSet<String>>;
```

With this structure, every key in the logging record, needs to be hased and then looked up in `FilteringMap`. Seems expensive to me and then keeping track of what has been matched, and what didn't is neccessary.

Instead I'd like it to be `Vec<(String, HashSet<String>)>`. The improvement would come from two things. First comparing strings is cheap, usually the first letter is different. Second, by using order of filter keys, there's no need to do O(N * M) comparison and only O(N) is required in the worst case. Maybe caching wouldn't be needed at all eliminating the problems that come with it (memory size/LRU, locking etc.).

Here's the example to explain (`Hs{ ... }` is shorthand for HashSet creation). Let's say the configuration is  like in the example you had in your gist.

```
[
 ("thread", HS{ "100", "200"}),
 ("packet", HS{ "send", "receive" })
]
```
It would meaning: record needs to first have `thread` key with one of given values, and afterwards must have `packet` with one of given values.


At `KVFilter` cretion, the vector would get reversed to:


```
[
 ("packet", HS{ "send", "receive" })
 ("thread", HS{ "100", "200"}),
]
```

Now for every record, we would first traverse from the (record key-value list (backward) + logger key-value list)  and match key  against `thread`. Once found, we check if value match. If it does, we keep going until key `packet` is found and so on. Once there is no more keys to look for, we know we have a match.

This way no additional datastructures are necessary to keep track of which keys were already checked. The only time hashing is done is when doing lookup of the value, on a matching key.

I am also thinking about adding a negative match. So the key value must **not** be within given values.

A bit of topic: I also wonder if `BTreeSet` wouldn't be faster than hashing for string lookup. `HashSet` is O(1) while `BTreeSet` O(log N), but I expect here the tree usually going to be tiny, so comparing keys log N times when N is tiny, might be actually faster then hashing a string.

**Comment by przygienda** [comment]
Well, result is the same and one can argue that HashMap will give AVG while the list may deteriorate to go through all the keys until found no match in worst case. I don't care particularly either way. Whatever you think gives the best perfo. Agree with the negative key, it's fairly practical sometimes, i.e. you want SOME stuff but then within it prune some (e.g. I want a subsystem traced but not its FSMs). The problem becomes if the same key has both, semantics are unclear ...

**Comment by dpc** [comment]
@przygienda Doesn't the current code have to go through all keys (minus caching on `id()`) in the worst case too?

**Comment by przygienda** [comment]
yeah, I do think you're right. Worse case is the same and my amortized case is bogus since the sequence of keys() will always be same out a HashMap ...

**Comment by dpc** [comment]
Released as: https://crates.io/crates/kvfilter . I guess we can close this issue.

**Comment by przygienda** [comment]
Yes, very cool, thanks. Saw you renamed the crate meanwhile ...

**Comment by dpc** [comment]
Yes. It wasn't like the rest. Sorry for the trouble.
