### ISSUE TITLE
Drain on root logger should not require 'static.

### ISSUE THREAD

**Issue by kdy1997** [slog-rs/slog#95]
Logger::root() requires ```drain: 'static```, but it seems unnecessary.
```rust
pub struct Logger {
    drain: Arc<Drain<Error=Never>+Send+Sync>,
    values: OwnedKeyValueList,
}
```
Logger struct does not have a same constraint, and no impl depends on 'static
And I think `root` must be a root of one logger hierarchy, not root of global.

### Example use case
Currently, I'm trying to capture logs as string to bypass https://github.com/rust-lang/rust/issues/12309. As it must be done once per #[test] fn, buffer string is not 'static. I can do it via thread_local!, but it's quite hacky as it depends on [bug][1].

```
---- definition::parser::tests::expansion_order_detection stdout ----
# I want to see logs for the test at here

```

[1]:https://github.com/rust-lang/rust/issues/17954

**Comment by kdy1997** [comment]
I will do it soon, and I want to know if you will merge it to slog.

(git clone from github is 8kb/s using msys2/windows 10)

**Comment by dpc** [comment]
I thought that `+ 'static` there was to prevent `Drain` from having outside references. I'll be happy to review the change and then we can discuss as I'm a bit confused now.

**Comment by kdy1997** [comment]
I was wrong about `'static`. Sorry for that.

And judging from my attempt to add lifetime to logger, it would break api compatability (if it's used in struct). I don't think it worth breaking all downstream crates. So I decided to leave slog as is, and implemented capture function using Arc<RwLock<Vec<u8>>>

```rust
let mut buf = Arc::new(RwLock::new(vec![]));

let _guard = PanicGuard { buf: buf.clone() };
let logger = init_slog(LogWriter { w: buf.clone() });

slog_scope::scope(logger, || op())
```

and it prints like (with color)
```sh
---- test name stdout ----
op: detecting expansion order
   DEBG [1] expr(1: g), depth: 2, max: 2
   DEBG [2] expr(2: g()), depth: 1, max: 2
   DEBG [0] expr(3: "test"), depth: 1, max: 2
   DEBG [3] expr(4: g()("test")), depth: 0, max: 2
```

Arc is used because I can't take drain back.


My problem is solved, but leaving it open because I'm not sure if it should required 'static.
Please feel free to close it.

**Comment by dpc** [comment]
Ah, now I see what you were aiming at exactly.

So yes - Loggers share one `Drain` by reference counting and can use it from different threads, and anyone that has `Logger` can create it's clone or a sub-logger, so adding lifetime to loggers wouldn't generally work.

Closing it, but always feel free to reopen in case something could be improved.
