### ISSUE TITLE
How does any level statements are removed in builds?

### ISSUE THREAD

**Issue by tredoe** [slog-rs/slog#99]
At section [Notable details](https://docs.rs/slog/1.4.0/slog/#notable-details), it says:

> by default removes at compile time trace and debug level statements in release builds

How is it done?

**Comment by dpc** [comment]
https://github.com/slog-rs/slog/blob/ce837155ee9db5b0bb9bf77798b73292d908901a/src/lib.rs#L311

**Comment by tmccombs** [comment]
Is that code guaranteed to be removed as dead code by the compiler?

**Comment by dpc** [comment]
Practically speaking, in release mode, according to my knowledge, yes. Since everything there is a compile time constant, it's one of the simplest optimizations to perform.

**Comment by dpc** [comment]
I have copied that method from `log` crate BTW. The only difference is that in `slog` the defaults are different.
